### ISSUE TITLE
Bootstrap.js

### ISSUE THREAD

**Issue by bashton** [jquery-ui-bootstrap/jquery-ui-bootstrap#102]
The jquery-ui-bootstrap doesn't seem to work with the bootstrap.js file.

**Comment by rigeliux** [comment]
Hi bashton, as virtuecenter( https://github.com/addyosmani/jquery-ui-bootstrap/issues/71#issuecomment-10921675) said, it's a problem between jquery ui button and bootstrap button javascript.

Solution:
Trough this link: http://twitter.github.com/bootstrap/customize.html build your custom bootstrap without the jQuery plugin "Buttons"

Hope this helps to anyone =)

EDIT:
Sorry, after i wrote this i came with additional info:
You can still use bootstrap button jaquery plugin:
1) Go to the bootstrap github repo ( https://github.com/twitter/bootstrap/blob/master/js/bootstrap-button.js )
2) copy the code in new js file.
3) Rename the jquery function ($.fn.button) to $.fn.buttonbootstrap or whatever you want.
4) Replace the name of the function in the lines below, and voila =)
