### ISSUE TITLE
jquery weekpicker conflict - css needs to be corrected

### ISSUE THREAD

**Issue by kashiif** [jquery-ui-bootstrap/jquery-ui-bootstrap#103]
Check the weekpicker based on jQueryUI weekpicker

http://igorzelmanovich.blogspot.com/2011/07/week-picker-using-jquery-ui-datepicker.html

When using it with jquery-ui-bootstrap, I had to modify the css (line 1021 master branch)

.ui-datepicker td .ui-state-default:hover { ...}

to 

.ui-datepicker td .ui-state-hover { ...}

**Comment by addyosmani** [comment]
Thanks for pointing this out. We'll address.

**Comment by gtraxx** [comment]
Line number in the new version: 1065
I'll do some tests :)

**Comment by gtraxx** [comment]
Bug fixed :D, I sent the changes
