### ISSUE TITLE
jQuery ui 1.9

### ISSUE THREAD

**Issue by gtraxx** [jquery-ui-bootstrap/jquery-ui-bootstrap#105]
Hello jQuery UI 1.9 is out today :)

jquery bootstrap is compatible with this version of jQuery UI ?

I'll update my new developments using jQuery bootstrap with jQuery UI 1.9

Best regards

**Comment by addyosmani** [comment]
This project hasn't been tested with 1.9 just yet, but if you could try it out and let us know how it goes that would be great :)

**Comment by gtraxx** [comment]
Ok I test tonight in a project to verify compatibility

best regards :)

**Comment by gtraxx** [comment]
I integrate jQuery UI 1.9, I test jquery ui dialog and the layout is correct.
Not detect the bug for now, I continue to do tests with firefox

I'll use tonight demos bootstrap to test all components :)

**Comment by addyosmani** [comment]
Thank you!

**Comment by gtraxx** [comment]
I started corrections in the CSS but how do I send them?
Should I make a fork and branch 1.9.0 ?

PS:  I changed the tabs, I start accordions :)

Best regards

**Comment by addyosmani** [comment]
If you could do that it would be amazing.

**Comment by gtraxx** [comment]
Here is the working branch for adaptations with jQuery UI 1.9.0

I added a new style sheet applied and changes in some files.
Corrections are applied jquery ui tabs + accordions

https://github.com/gtraxx/jquery-ui-bootstrap/tree/Boostrap-1.9.0

Best regards

**Comment by gtraxx** [comment]
I continue, I just finished an example for jquery ui menu that I built in the index.html file (it does not exist)
There were a lot of changes to make it compatible, everything will be available on my fork.
I'll keep you posted on the progress of changes / adjustments
;)

**Comment by addyosmani** [comment]
Awesome. Thanks @gtraxx :) I'm going to test out your fork today. Would be really happy to pull in some of these changes when its more stable.

**Comment by gtraxx** [comment]
I still have not sent all ! 
I can send it tonight with changes in jquery ui menu :)

Here is a capture image with jquery ui menu: http://www.imagup.com/data/1165064256.html

**Comment by jvosloo** [comment]
This is awesome @gtraxx ! Thank you very much for you efforts.

**Comment by gtraxx** [comment]
No problem, I added ui menu and ui spinner in the demos.
I'll do tonight ui tooltip, then once everything stabilized I propose to merge
:)

**Comment by gtraxx** [comment]
Hello could you create the branch 1.9.0 so that I can send you the files?

I add the following demos in the file index.html :
- tooltip
- spinner
- menu

I could send the files directly in the branch :)

Best regards

**Comment by addyosmani** [comment]
@gtraxx I've added you as a project collaborator :) You should have access to push to or create new branches now. Can't wait to see your work on this in master! \o/

**Comment by addyosmani** [comment]
@gtraxx I have a suggestion: what do you think about us:
- Created a gh-pages branch
- Moving the contents of master to this branch
- Moving the 1.9 work you've done into a beta folder of this new branch

The idea would be that any members of the community could easily see the state of dev work as well as stable.

Did you have any interest in helping work on getting parity with Bootstrap 2.x? :)

**Comment by gtraxx** [comment]
Ok I will send the changes to the master because I have a backup file of version 1.8.16.
Those using a previous version of jQuery UI will use the old files.
I am willing to participate in the next development version 2.0 :)

**Comment by addyosmani** [comment]
That's awesome! I see that we now have 1.9 in master so lets close this and continue work on improving the project in specific issues. Please feel free to post new tickets for any specific areas you'd like addressed :)
