### ISSUE TITLE
Button inside an accordion

### ISSUE THREAD

**Issue by guillermovil** [jquery-ui-bootstrap/jquery-ui-bootstrap#106]
Good afternoon, I'm trying to put a button "success" inside an accordion , the button is created but not green. 
I also tried to create as class primary, but still gray (not blue). If I put it outside the accordion, so the button looks good.

What could be happening?

Thank you.

**Comment by valsou** [comment]
As i said in this topic (https://github.com/addyosmani/jquery-ui-bootstrap/issues/98) this is a CSS problem.

I didn't already make an accordion but i presume prefix to add is ".ui-accordion-content".

-> ".ui-button-primary, .ui-accordion-content .ui-button-primary"
-> ".ui-button-success, .ui-accordion-content .ui-button-success"
-> ".ui-button-error, .ui-accordion-content .ui-button-error"

Have a nice day.

**Comment by guillermovil** [comment]
Yes! Thank you very much

**Comment by gtraxx** [comment]
Css classes have changed since the upgrade to jquery ui 1.9.0
If there are problems with this version do not hesitate to make a ticket
Best regards

**Comment by addyosmani** [comment]
Closing as resolved for now.
