### ISSUE TITLE
IE problems

### ISSUE THREAD

**Issue by guillermovil** [jquery-ui-bootstrap/jquery-ui-bootstrap#110]
Hello, can I use jquery ui bootstrap theme with good result if I avoid to call bootstrap.css?
In my code I call only    <link type="text/css" href="css/custom-theme/jquery-ui-1.8.16.custom.css" rel="stylesheet" />.
I have good result in FF and chrome but I can´t see dome effect in IE like input blue borders.
Thank you in advance.

Guillermo

**Comment by gtraxx** [comment]
Hello, do you have a screenshot?
with any version of bootstrap ? jQuery UI 1.9.0 or 1.8.26 ?

Best regards

**Comment by addyosmani** [comment]
As mentioned if you can post us a screenshot of the issue with the version of IE you're having trouble with we're happy to help.

**Comment by guillermovil** [comment]
thank you for your answer, 
Please try this url in IE: http://www.mda-fmc.com.ar/ then try in FF or Chrome. can you see the diference? what happend with some effect in IE?

**Comment by gtraxx** [comment]
Hello, 
what effect ?
I'll watch the borders radius for the elements but only for IE 9, it is not available for older versions of IE
Is this the problem identified ?
see compatibility : http://caniuse.com/
:)

**Comment by guillermovil** [comment]
Thank you gtraxx, i can´t see blue active border in inputs. And the vertical alignement is not like FF or Chr

**Comment by gtraxx** [comment]
I just checked you are using an older version of jQuery UI (1.8.18) and bootstrap.
Maybe the bugs have been fixed, the demonstration of jquery bootstrap works and doesn't return error
See also components with inheritance ;)

**Comment by guillermovil** [comment]
Ok, 
Sorry I very new in that type of development.
I like jquery ui and I like bootstrap design
What I need to call in my pages to make my application look good with jquery ui functionality and bootstrap look? I must to call some bootstrasp-.....js? I must to call bootstrap.css? OR I only need to call jquery-ui-1.8.16.custom.css and jquery-ui-1.8.16.custom.min.js?
Please excuse my ignorance and my terrible English.

**Comment by addyosmani** [comment]
Closing for now.
