### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by addyosmani** [jquery-ui-bootstrap/jquery-ui-bootstrap#112]
@gtraxx I think we should decide on a target date for the next release. We don't have to have a version with all the bells and whistles of Bootstrap 2.0 but even having a version stable enough to use with it for now would be a great start. I think your UI version updates would also be welcome.

What do you think?

**Comment by gtraxx** [comment]
Yes it is a good idea.
I can work on a version compatible with the latest version of bootstrap and make all necessary tests.

What do you think ?

**Comment by addyosmani** [comment]
That would be fantastic @gtraxx. How would you feel about us targeting November 16th for having a first version ready ? It might be possible to get something done sooner but I felt two or so weeks could be doable.

I'm going to update the readme to include you in the team for this project. You've certainly earned it with your contributions :)

**Comment by gtraxx** [comment]
Thank you, I'll check with my calendar but it will be possible :)

#### First version:

It will be compatible with the latest version of bootstrap (compatibility test)

#### Future version:
- A full version features Twitter bootstrap with jQuery UI and additional plugins.
  :D

**Comment by addyosmani** [comment]
That sounds perfect :)

**Comment by gtraxx** [comment]
Hello, I work on the project this Saturday afternoon.
I fix some bugs that I sent.
PS: I received your book "javascript design patterns" 
This is an excellent book :)

**Comment by addyosmani** [comment]
Oh, thanks @gtraxx :) I'm glad you liked the book! I also really appreciate the bug fixes. You rock. I can't wait for us to get the next release out. Will do some further cross-browser testing this weekend and try to help with stability.

**Comment by copasetickid** [comment]
Hi @addyosmani, I'm new to contributing to open-source projects and I wanted to if you are  still seeking contributors for this jquery-ui-bootstrap project?

**Comment by benjamin-bd** [comment]
Hi all,

I have gone through all the change between jqueryui 1.9.0 and 1.91 (see
page http://jqueryui.com/changelog/1.9.1/).

I hope this list will help you when you will switch from 1.9.0 to 1.9.1.

There is only a few changes on the css (all the other one are only js):
Autocomplete: Set the top position of the menu so that the menu doesn...
https://github.com/jquery/jquery-ui/commit/1ee090ea9e03c800a764d992506869384409bdb6

Spinner: Remove ui-state- classes from spinner, along with the backgr…
https://github.com/jquery/jquery-ui/commit/112185ec8ddb7f0849fa40e7b1409e28153555f8

Spinner: Remove z-index from buttons. Whatever the original purpose, …
https://github.com/jquery/jquery-ui/commit/ac43938c8c1c908546cdb967dce11806bf2b4197

Tooltip: Position below the element and set a max width of 300px to m…
https://github.com/jquery/jquery-ui/commit/7af1ec727bcca8367e804cea77b9dd238b1c0d69

CSS: Apply opacity to absolutely positioned ui icons in IE8. Fixed #6…
https://github.com/jquery/jquery-ui/commit/fe1ecf97e01f6b9e6041ae324deafb69063d1c9c

Theme: Apply color to default link style in ui-state-hover. Fixes #76…
https://github.com/jquery/jquery-ui/commit/cb57f223e0390266de5cad356477178e9112df41

https://github.com/jquery/jquery-ui/commit/cb57f223e0390266de5cad356477178e9112df41
thttps://github.com/jquery/jquery-ui/commit/cb57f223e0390266de5cad356477178e9112df41hanks
for all your work,
Benjamin

**Comment by gtraxx** [comment]
Thank you I analyze patches tomorrow and I will work ;)

**Comment by addyosmani** [comment]
@benjamin-bd Thanks so much! These will definitely come in useful :)

**Comment by addyosmani** [comment]
Gerits, do you think we should come up with a final list of issues we would
like to address for the next release so we can capture them in a milestone?
:)

The above looks like a good start. I can break them down into individual
issues we knock out the door.

**Comment by gtraxx** [comment]
yes I check every message and correct any bugs or issues
I'll fix everything at once, and check the problem with IE
:)

**Comment by gtraxx** [comment]
Hello, I just fix some bugs and change the layout.
I change the bootstrap version (2.2.1) and fix the problem in HTML + CSS :)

**Comment by addyosmani** [comment]
@gtraxx That's awesome! Thank you. I will take a look at the changes this evening. Do you need any help with cross-browser testing at all? I'm happy to assist with making sure everything works as expected there.

**Comment by gtraxx** [comment]
@addyosmani 

> Do you need any help with cross-browser testing at all?

Yes, we need to test and see for IE9 border-radius for the missing elements in different
But I think we split the sample into different pages for examples complete
To analyze :)

**Comment by benjamin-bd** [comment]
Just for your information I have also a personal github account. the
username is tolbard

**Comment by gtraxx** [comment]
Hi,
Good news 
Font awesome (http://fortawesome.github.com/Font-Awesome/) works well with jquery ui bootstrap :+1: 
I use:
- Bootstrap
- Font awesome
- JQuery ui bootstrap
  I can verify each bug and fast forward through the changes jquery ui bootstrap :)

Best regards
Aurelien

**Comment by addyosmani** [comment]
That is awesome news! :) Thanks for testing and confirming @gtraxx. Should we consider bundling or just mention on the wiki the projects work well together?

**Comment by addyosmani** [comment]
@gtraxx Based on the list mentioned earlier in this thread, what remaining issues do you think we should try tackling for the release? It would be great to get something out before Christmas so folks have a chance to test / report any problems that might be outstanding.

**Comment by addyosmani** [comment]
Pre-release questions:
- Do we work out of the box with Bootstrap 2.x without breaking the scaffolds/grid layouts?
- Does our CSS break its [Base CSS](http://twitter.github.com/bootstrap/base-css.html)?
- Are our default styles for components up to date with the Base CSS > [default styles](http://twitter.github.com/bootstrap/base-css.html#forms) (e.g form select, buttons, inputs etc)
-  Are the button dropdowns with selects possible using jQuery UI and our CSS? http://cl.ly/image/452q1A2l1V19 If so, do we allow this to be done left and right (or does jQuery UI) http://cl.ly/image/3w212O3x3q0i
- Are our validation styles for forms/inputs up to date? http://cl.ly/image/3Z0v2d0x0O03
- Do we support the same disabled button states? http://cl.ly/image/2E3q423q0Q1a
- Are our button icons compatible with the latest CSS? http://twitter.github.com/bootstrap/components.html
- Are our drop-down buttons using the latest styles? 
- Do we support sub-menus with similar styles using jQuery UI menu and Bootstrap CSS?
- Do we support multiple button groups? 
- Are our drop-down button variations up to date? 
- Do we support the basic pill menus using jQuery UI tabs? 
- Are we supporting the latest basic navbar CSS? 
- Do our components work inside nav toolbars?

**Comment by gtraxx** [comment]
Some javascript component are in conflict:
- JQuery ui button / Bootstrap button
- Tooltip

The solution is to download bootstrap without components button and tooltip but only in javascript.

> Are we supporting the latest basic navbar CSS? 

Yes the latest basic navbar is supported

I'll check the other questions :)

**Comment by addyosmani** [comment]
How would you feel about us restructuring the project/demo page a little more 
like http://mgcrea.github.com/angular-strap/?

I like the way it follows Bootstrap's own design yet manages to keep it's own
identity :)

Happy new year!

**Comment by jodydonetti** [comment]
We should also take a look at http://aristath.github.com/elusive-iconfont/ .
It seems to be as good as FontAwesome, but with a larger icon set and different licensing (CC vs SIL, dunno which one is better for the project).

**Comment by gtraxx** [comment]
Hi,
I'll look for a layout but be an image header with a logo ?

@njy great the icons

Happy new year :)

**Comment by addyosmani** [comment]
It would pretty much be an image header, logo and menu to allow browsing through the different components. I would almost just fork what they've created and use it as a starting point which we can iterate on. 

How would that sound? :hatched_chick:

On the rest of the release, I think that if we're able to get some of the list of questions above answered (or issues created to fix where relevant) we'll be in a great position. I'll help with testing out some of those this week.

**Comment by gtraxx** [comment]
Hi, Addy
Who can create the header image?
Ok I'm starting the new examples based on bootstrap website and I check the issues to make corrections :)

**Comment by addyosmani** [comment]
I can do that :)

**Comment by gtraxx** [comment]
Ok no problem, when the image is ready sent me the link :)

**Comment by gtraxx** [comment]
Hi @addyosmani , I am the first page with the menu this weekend using the bootstrap banner.
I will make a simple menu and easy to use for users who visit the documentation
I will replace when you send yours :)

**Comment by addyosmani** [comment]
Thanks @gtraxx! I worked on this the other day but need to resize to the correct size. Will send over as soon as I get on my other box.

As I was mentioning on the other threads, I'd like to get more people involved in the project to help
us get the next release out.

To make sure there are specific issues they can help with, I'd like us to refine what we think needs to
be done. Could you add the things you'd like done to this thread?

**Comment by addyosmani** [comment]
Initial list
- [ ] Add Grunt build process
- [x] Fix JavaScript conflicts with jQuery UI Button / Bootstrap button
- [x] Fix conflicts with tooltips
- [x] Confirm we work out of the box with Bootstrap 2.x without breaking the scaffolds/grid layouts
- [x] Confirm we work with Bootstrap's [base CSS](http://twitter.github.com/bootstrap/base-css.html)
- [ ] Are our default styles for components up to date with the Base CSS > [default styles](http://twitter.github.com/bootstrap/base-css.html#forms) (e.g form select, buttons, inputs etc)
- [ ] Are the button dropdowns with selects possible using jQuery UI and our CSS? http://cl.ly/image/452q1A2l1V19 If so, do we allow this to be done left and right (or does jQuery UI) http://cl.ly/image/3w212O3x3q0i
- [ ] Are our validation styles for forms/inputs up to date? http://cl.ly/image/3Z0v2d0x0O03
- [ ] Support the same disabled button states http://cl.ly/image/2E3q423q0Q1a
- [x] Are our button icons compatible with the latest CSS? http://twitter.github.com/bootstrap/components.html
- [x] Are our drop-down buttons using the latest styles? 
- [ ] Support sub-menus with similar styles using jQuery UI menu and Bootstrap CSS
- [x] Support multiple button groups? 
- [ ] Make sure our drop-down button variations up to date with Bootstrap latest
- [x] Support the basic pill menus using jQuery UI tabs
- [x] Support the latest basic navbar CSS
- [x] Support our components working inside nav toolbars
- [x] Project Documentation
- [x] New homepage
- [ ] Move over to using SASS?

**Comment by gtraxx** [comment]
I take care of all items checked.

We work with the latest version of bootstrap but there are incompatibilities with javascript.
- Tooltip
- Button

So I tested several configurations and I found a balance in the use of bootstrap and jQuery UI
I already working on new documentation in me based on official Bootstrap

**Comment by addyosmani** [comment]
@gtraxx you rock. Thanks so much for helping take care of those items. I'll make sure we find owners for the others!

**Comment by gtraxx** [comment]
ok :)
I also tested for use holder.js (new version) in the documentation, I wrote an article in French with some examples on the my new blog :)  (http://blog.aurelien-gerits.be/2013/01/17/remplacer-les-images-avec-des-canvas-via-holder-js/)

**Comment by addyosmani** [comment]
I would like to target getting a new release out in the next two weeks.I think the script split and a few more docs would help. I've also pinged on a few threads to see what you think of remaining feature requests.

One thing we probably want to do is mention filesize of our solution if using it all with minified versions of the main files to use. Sound good? :)

**Comment by gtraxx** [comment]
I prepare a version minified scripts and separation.
