### ISSUE TITLE
jquery ui menu

### ISSUE THREAD

**Issue by guillermovil** [jquery-ui-bootstrap/jquery-ui-bootstrap#113]
Good evening, I have a problem with the menu design.
I use jquery ui 1.9 and the bootstrap theme 1.9.
There is a visual behavior that I don't like: the options menu and menu container change the size. Check it out at
http://mda-fmc.com.ar/oplab/test.php
Please move the mouse from the "Postulantes" option to the "Quienes somos" option and  will notice that I say. What I have to correct in the css?
I hope you can help me.
Thank you very much and sorry for my bad English

**Comment by gtraxx** [comment]
Hello, I will identify the problem and make the correction.
This is the class "active" which decreases the margin.
Best regards

**Comment by gtraxx** [comment]
Bug fixed :)

**Comment by guillermovil** [comment]
ok, i make some correction in .ui-menu .ui-menu-item a.ui-state-focus,
.ui-menu .ui-menu-item a.ui-state-active but I have another 

thank you very much, I could fix the problem but I still have some unexpected and ugly effects when I move from main to submenu. the size of the main menu is changed.
Could you tell me how you found the other problem? Thank you in advance

**Comment by gtraxx** [comment]
Bug fixed :D

**Comment by guillermovil** [comment]
thank you gtraxx Could you tell me how you found the other problem?
Where is de css fixed?

**Comment by gtraxx** [comment]
I analyze and do tests to modify the CSS.
Changes are sent to the trunk :)

**Comment by guillermovil** [comment]
thank you very much

**Comment by gtraxx** [comment]
:)
