### ISSUE TITLE
IE9 Border Radius

### ISSUE THREAD

**Issue by jasonkessel** [jquery-ui-bootstrap/jquery-ui-bootstrap#115]
When will the border-radius be supported in IE9? IE9 supports border-radius css, so it seems like it should be supported in JQuery UI Bootstrap.

**Comment by gtraxx** [comment]
Hi, the style sheet "jquery.ui.1.9.0.ie.css" change the border-radius to 0
Have you added ?
I have to check with windows to see the behavior

**Comment by jasonkessel** [comment]
Yeah, I tried this about a year ago, but could never get it to work in IE 9. I remember you recommending changing that .ie.css file, but even then, I had no border-radius in IE9. Seems like there hasn't been any progress made on that front. I love the way this theme looks in all browsers except for IE9.
    Jason Kessel
Marketing Communications Manager, GreenRope.com

**Comment by gtraxx** [comment]
Change the line in the demo:

``` html
<!--[if IE]>
 <link rel="stylesheet" type="text/css" href="css/custom-theme/jquery.ui.1.9.0.ie.css"/>
<![endif]-->
```

try with:

``` html
<!--[if lt IE 9]>
<link rel="stylesheet" type="text/css" href="css/custom-theme/jquery.ui.1.9.0.ie.css"/>
<![endif]-->
```

**Comment by jasonkessel** [comment]
Other than the space before <link, what's the difference in those lines of code?
    Jason Kessel
Marketing Communications Manager, GreenRope.com

**Comment by jasonkessel** [comment]
Ok, I went to http://addyosmani.github.com/jquery-ui-bootstrap/ with IE 9 in Windows 7. I found the line of code for the IE9 css using the IE dev tools. It's set to 1.8.16 currently. So, I changed it to 1.9.0. The results... only _some_ things are rending the border radius. The color buttons, the yellow and red highlights and error and a few other things are still squares.
    Jason Kessel
Marketing Communications Manager, GreenRope.com

**Comment by addyosmani** [comment]
The difference is the `lt IE 9` (i.e less than IE9)

**Comment by gtraxx** [comment]
Bug is fixed (https://github.com/addyosmani/jquery-ui-bootstrap/commit/3896ff4df55f1bba7901e429cd4ac39c9ef2395f)
;)

**Comment by jasonkessel** [comment]
Thanks. I assume we need to download and install the latest version of the bootstrap theme?
    Jason Kessel
Marketing Communications Manager, GreenRope.com

**Comment by gtraxx** [comment]
Yes :) (https://github.com/addyosmani/jquery-ui-bootstrap/archive/gh-pages.zip)
Best regards
