### ISSUE TITLE
button with icon issue

### ISSUE THREAD

**Issue by Cipa** [jquery-ui-bootstrap/jquery-ui-bootstrap#117]
Hi,

I am sure you know about this problem and I was wondering if it was fixed. The problem is that icons in buttons break the button layout: the text and the icon are one under other instead of next to each other.

Here is a test case:

html  - in index.html
`<button class="next">Next</button>`

js - in the demo.js

```
    $("button.next").button({
        icons: {
            secondary: "ui-icon-triangle-1-e"
        }
    }).click(function(){
        alert('test');
    });
```

Was this fixed in any of the development branches. My search returned nothing.

Thank you

**Comment by addyosmani** [comment]
This is still present, but I really want to get it fixed soon. Will try to take a look at it this weekend.

**Comment by gtraxx** [comment]
Bug fixed in new demo :)
