### ISSUE TITLE
Slider needs jquery 1.6.2!

### ISSUE THREAD

**Issue by ghost** [jquery-ui-bootstrap/jquery-ui-bootstrap#118]
I'm using backbone so I have already jquery 1.8.x loaded.

However, the slider of jquery-ui does not work once I want to drag it giving the following error:

```
Uncaught TypeError: Cannot call method 'addClass' of undefined 
  d.widget._mouseCapture 
  b.widget._mouseDown 
  (anonymous function) 
  jQuery.event.dispatch    
  elemData.handle.eventHandle
```

Problem is solved if I load `jquery-1.6.2` .. 
The question I ask is: Why?! Can there be a workaround for it?

Cheers!

**Comment by ghost** [comment]
ahhh wait, can jquery-ui work with newer version of jquery?

**Comment by ghost** [comment]
Ok, problem solved. I downloaded the latest `jquery-ui-1.9.1` from the [website](http://jqueryui.com/).
I also used `jquery-1.8.2`.

With these files, the slider and backbone work together smoothly so far.

I apologies for posting the issue before doing the research. Yet, this brings up the question, why is this repo still using and older jquery-ui verison that requires and older jquery version?

Cheers and Thank you!

**Comment by gtraxx** [comment]
The current version in the repository using the latest version of jquery and jquery ui
I need to update jquery 1.9.0 => 1.9.1
;)
Best regards

**Comment by addyosmani** [comment]
We will take care of this before the next release :)

**Comment by gtraxx** [comment]
Look in the index.html file, we use jquery 1.8.3 and jquery ui 1.9.2
https://github.com/addyosmani/jquery-ui-bootstrap/blob/master/index.html
Changes are needed in the template jquery ui bootstrap
https://github.com/addyosmani/jquery-ui-bootstrap/blob/master/css/custom-theme/jquery-ui-1.9.2.custom.css
:)

**Comment by addyosmani** [comment]
@gtraxx Do you know if this bug is still present?

**Comment by gtraxx** [comment]
The bug is fixed but it would do more tests with the latest version of jQuery UI Bootstrap and Backbone

**Comment by addyosmani** [comment]
Cool. SGTM.

**Comment by addyosmani** [comment]
Good to close?

**Comment by gtraxx** [comment]
Yes ;)
