### ISSUE TITLE
Wijmo menu: border tweaks

### ISSUE THREAD

**Issue by addyosmani** [jquery-ui-bootstrap/jquery-ui-bootstrap#12]
From twitter:

Just 2 little issues on the menu: The border-radius on top left corner & padding:

http://t.co/h71aRGzU

**Comment by Francisc** [comment]
Hey,

The top-left corner should not be rounded or did you mean something else?

**Comment by addyosmani** [comment]
@Francisc I meant the top-left and right corners of the Wijmo menu need to be tweaked so that they aren't using a custom border radius (ie. are set to 0). At the moment with both top corners rounded it looks a little off.
