### ISSUE TITLE
less file for jquery-ui-1.9.0.custom.css

### ISSUE THREAD

**Issue by styts** [jquery-ui-bootstrap/jquery-ui-bootstrap#120]
It would be desirable to style the colors, etc. of the elements... Is there a less file somewhere from which the css file was generated?

**Comment by gtraxx** [comment]
No idea, I do not care less which version is not yet updated to jQuery 1.9.x
Must be adapted version 1.9 for less

**Comment by addyosmani** [comment]
We have an older set of less files I'm branch but won't be exploring an official less version until the release after next.
