### ISSUE TITLE
How to integrate?

### ISSUE THREAD

**Issue by cherchyk** [jquery-ui-bootstrap/jquery-ui-bootstrap#122]
Can you please describe how to integrate code into existing project?

I don't want blindly copy your files but only changes you did.

**Comment by gtraxx** [comment]
Hi,
What type of project?
You can watch the demo (index.html) but here is a simple example
The theme is in the folder: custom-theme

``` html
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>jQuery UI Bootstrap</title>
    <link type="text/css" href="css/custom-theme/jquery-ui-1.9.2.custom.css" rel="stylesheet" />
</head>
<body>
<p>Your content</p>
<script type="text/javascript" src="js/jquery-1.8.3.min.js"></script>
<script type="text/javascript" src="js/jquery-ui-1.9.2.custom.min.js"></script>
</body>
</html>
```

Best regards

**Comment by cherchyk** [comment]
I think the right approach could be to have jquery-ui and bootstrap files untouched and then jquery-ui-bootstrap implementation in the separate file(s).  Right know I do not see what was modified. Does jquery-ui-bootstrap change jquery or jquery-ui or bootstrap or all of them.
It is risky to take modified libraries from here because I do not know what was changed and if that change was properly tested.
Do you understand what I mean?

**Comment by gtraxx** [comment]
Hello, the original files are not changed, they are intact
This is a template jquery ui so it uses its own CSS as skin

**Comment by addyosmani** [comment]
@cherchyk did that answer your question?
