### ISSUE TITLE
accordion autoHeight

### ISSUE THREAD

**Issue by afonsoadson** [jquery-ui-bootstrap/jquery-ui-bootstrap#123]
Hey,  i've been trying to change the height of the accordion so it adjusts dinamically to the contentt in it. i'm not entirely sure where to put the autoHeight:"false" command inside the jquery -ui1.9.2.custom.min.js. Any help would be much appreciated. Great Job on the bootstrap. It looks great.

**Comment by gtraxx** [comment]
Hi, 
You can set the height in jquery ui 1.9.x following API:

http://api.jqueryui.com/accordion/#option-heightStyle

### Example:

``` javascript
$( ".selector" ).accordion({ heightStyle: "fill" });
```

Best regards :D

**Comment by addyosmani** [comment]
@gtraxx Thanks for replying. Is this good to close?

**Comment by afonsoadson** [comment]
yes. thank you for the help

**Comment by gtraxx** [comment]
@addyosmani  Oops I did not press the right button lol

**Comment by addyosmani** [comment]
No worries!
