### ISSUE TITLE
Tabs with close icon

### ISSUE THREAD

**Issue by marvi** [jquery-ui-bootstrap/jquery-ui-bootstrap#124]
Thanks for your work!

I am trying to implement the adding/closing of tabs example (http://jqueryui.com/tabs/#manipulation) but I get a line wrap in the li tag.

To reproduce in index.html, add a close icon after the link on line 95:

``` html
<li><a href="#tabs-1">First</a><span class="ui-icon ui-icon-close">Remove Tab</span></li>
```

**Comment by gtraxx** [comment]
Hi marvi , I will check and fix the bug
I'll add a demo for this part

:)

**Comment by gtraxx** [comment]
The bug is fixed and added in the demo :)

View commit description:

https://github.com/addyosmani/jquery-ui-bootstrap/commit/77d9931a79dbae46fce84a13849b2d4b2b8cb929

It's ok ?

Best regards

**Comment by marvi** [comment]
Looks great. Thanks!

**Comment by gtraxx** [comment]
thanks :)
