### ISSUE TITLE
jQuery UI Autocomplete

### ISSUE THREAD

**Issue by dkleehammer** [jquery-ui-bootstrap/jquery-ui-bootstrap#125]
Are there any updates coming soon that contain bootstrap visuals for autocomplete?  I'm really digging this project, but I need autocomplete to fit in with the rest of my bootstrapped site.

edit: just went through the css and I noticed that autocomplete and the menu items are there, but the hover/active states aren't working on the menu items for me.  In order to integrate with my project, I've only replaced the stylesheet from smoothness to this theme; did I missing something?  I'm noticing that some of css classes from the custom-theme are working, but I'm mainly only concerned with the autocomplete at this time, so I haven't checked out all classes.

Thanks,

dk

**Comment by gtraxx** [comment]
Hello, there's a demo of the autocomplete in architecture.
But if there are bugs I will correct. :)

**Comment by gtraxx** [comment]
The autocomplete with style sheets (jquery-1.9.2.css) works with hover
Have you tested with an example?

![autocomplete-jquery-bootstrap](https://f.cloud.github.com/assets/356674/7770/d7e3aeaa-4440-11e2-9d96-f9eeabdcf4b4.png)

**Comment by dkleehammer** [comment]
I was not using the newest version.  I used the download link from the demo site.  I switched to 1.9.2 and it's working now.  Thanks!

**Comment by gtraxx** [comment]
no problem :)
