### ISSUE TITLE
usage of Font Awesome icons

### ISSUE THREAD

**Issue by OlegKi** [jquery-ui-bootstrap/jquery-ui-bootstrap#127]
Hello!

What do you think about the usage of [Font Awesome icons](http://fortawesome.github.com/Font-Awesome/#all-icons) at least as additional option? It could be a cool feature.

Look at [here](http://stackoverflow.com/a/13865495/315935) for an example of advantages of usage Font Awesome icons in jqGrid which is jQuery plugin which is oriented on jQuery UI Themes CSS. In the referenced answer I had to change some CSS classes from the standard jQuery UI Theme to the corresponding Font Awesome classes. If it would be exist some jQuery UI Themes (like youth for example) then it would be enough just use the jQuery UI Theme. It would be cool!

Best regards
Oleg

**Comment by jodydonetti** [comment]
I've integrated FontAwesome in the app i'm developing with great success, with both jQuery UI and Bootstrap.

The bootstrap guys talks about problems with IE7, if i remember correctly, but they were talking about GlyphIcons, not FontAwesome. In any case, i'll take a shot at it.

**Comment by OlegKi** [comment]
@njy: I don't tested Font Awesome with IE7 myself, but the Font Awesome v2.0 now supports IE7 (see [here](http://fortawesome.github.com/Font-Awesome/)). There are special `font-awesome-ie7.css` which can be inserted for example with the code like



```
<!--[if IE 7]>
    <link rel="stylesheet" href="css/font-awesome-ie7.css">
<![endif]-->
```

Moreover **it's not really required to use neither Bootstrap nor LESS to be able to use Font Awesome**. So everybody who use jQuery UI only can use the fonts. See for example [the demo](http://www.ok-soft-gmbh.com/jqGrid/FortAwesome/FortAwesome.htm) which I referenced. It uses only `font-awesome.css`.

**Comment by gtraxx** [comment]
Hello, I'm testing with Awesome Font and everything works fine.
View issues : 
https://github.com/addyosmani/jquery-ui-bootstrap/issues/112
:)

**Comment by OlegKi** [comment]
@gtraxx: Sorry, but probably I understand you not exactly. I supposed that jQuery UI Bootstrap Theme can be used _without_ Bootstrap or LESS. It seems that it can be used just like any other jQuery UI Theme.

[The issues #112](https://github.com/addyosmani/jquery-ui-bootstrap/issues/112) seems to me like pure discussion in context of LESS.

All images used in original jQuery UI Themes distributed by jQuery UI contains PNG files. [The home page](http://addyosmani.github.com/jquery-ui-bootstrap/) of jQuery UI Bootstrap has the same disadvantage. If I look at the page with zoom 400% for example the icons looks not attractive.

What I search is some jQuery UI Theme which uses Font Awesome icons in the CSS. Your project jQuery UI Bootstrap seems be at the first look mostly close to the goal, but to be able to use vector icons one need to have `jquery-ui-1.9.2.custom.css` where all icon classes (`ui-icon-carat-1-n`, `ui-icon-carat-1-ne` etc) are implemented not like [here](https://github.com/addyosmani/jquery-ui-bootstrap/blob/master/css/custom-theme/jquery-ui-1.9.2.custom.css#L206) using `url(images/ui-icons_222222_256x240.png)`. Instead of that one need to use `url('../font/fontawesome-webfont.eot')` and for example something like `{ content: "\f0d8"; }` (see [here](https://github.com/FortAwesome/Font-Awesome/blob/master/css/font-awesome.css#L283) the definition of the class `icon-caret-up` of Fort Awesome which corresponds to `ui-icon-carat-1-n` from jQuery UI). Mostly **different names** of classes from Font Awesome CSS and jQuery UI CSS is the problem.

In the way one could provide jQuery UI Theme with _vector icons_. So everybody who has existing solution which uses jQuery UI Theme (for example everybody who use jqGrid) could bust include the Theme to have advantage of perfect scaleable icons.

Regards
Oleg

**Comment by jodydonetti** [comment]
@OlegKi

> Moreover it's not really required to use neither Bootstrap nor LESS to be able to use Font Awesome

Yeah, i know, but since we are talking about "jQuery UI **Bootstrap**" (emphasys mine) i was just pointing out possible problems.

Anyway, i'm using it with both bootstrap and jquery ui, and it seems to work just very very fine.

Cheers

**Comment by addyosmani** [comment]
My position is that we're generally now targeting IE8+ in terms of support on that front, but it's good to hear that Font Awesome works on older browsers too. I'd be happy for us to land support for it if we can get a pull request in.

@gtraxx is this something you feel comfortable landing based on your current tests or do you need more help with it?

**Comment by OlegKi** [comment]
@addyosmani: The support of IE7 is not important for me. It's just nice to have feature. My main question was: is it possible to use vector icons (Font Awesome icons) instead of raster icons from PNG pictures used currently. The most interest have _pure CSS solution_.

**Comment by jodydonetti** [comment]
:+1: to let IE7 die slowly and painfully, if it causes any kind of pain

**Comment by addyosmani** [comment]
I think it's definitely possible and I'd be happy for us to move in the direction of using vector icons.

**Comment by gtraxx** [comment]
@addyosmani  The integration "Font Awesome" with "jquery ui" should not be a problem few lines to add to the CSS.
I put in the work to do ;)

**Comment by addyosmani** [comment]
Excellent! Thanks :)

**Comment by OlegKi** [comment]
Thank you very much!

**Comment by addyosmani** [comment]
@gtraxx Did we integrate Font Awesome the last time we looked into this? If not, have you already done this locally or would you like to see if someone else on this thread could help?

**Comment by gtraxx** [comment]
Hi @addyosmani , I already do local testing.
Question:
Should I replace the original use of icons or use jQuery UI Font Awesome extra?
It is very important :)

**Comment by addyosmani** [comment]
I would like to maintain parity with Bootstrap itself where possible. Just checked and they're using glyphs. How about we use Font Awesome extra and consider making it a default after the next release if people want it? :)

**Comment by gtraxx** [comment]
ok, I'll work :)

**Comment by addyosmani** [comment]
Thanks!

**Comment by gtraxx** [comment]
Hi @addyosmani ,
I will send the changes to work with "Font Awesome".

#### Example :

``` javascript
$("#mybutton").button({
       text: false,
       icons: {
        primary: "icon-github"
       }
});
```

You can always work with jQuery UI icons without problem
I send changes tonight :D

**Comment by gtraxx** [comment]
"Font awesome" work with split button, button with icons and toolbar (https://github.com/addyosmani/jquery-ui-bootstrap/commit/3c39a0cd46dd1e0236dd07de3565efa4f87ed304)
:+1:

**Comment by addyosmani** [comment]
Yay! that is really awesome. Thanks for checking!

**Comment by gtraxx** [comment]
New demo with "Font Awesome" in extra page (http://addyosmani.github.com/jquery-ui-bootstrap/extra.html)
I added a note in the css file and fixed some bugs :)

**Comment by addyosmani** [comment]
Ahhhh. I love them. Great work, @gtraxx! :)

**Comment by addyosmani** [comment]
Hey, wanna update the copyright notice at the bottom + readme to include your name? You're practically co-maintainer right now.

**Comment by gtraxx** [comment]
Yes, but what can I write? 
Aurélien Gérits co-maintainer ?
:)

**Comment by gtraxx** [comment]
Hi @addyosmani ,
I made the changes in the footer :)
Is that correct ?

Do you want to change the README?
Can I add a changelog :)

**Comment by OlegKi** [comment]
Thank you for very good job!

I have to mention that one need change a little the value of `margin-left` for the icons on [the page](http://addyosmani.github.com/jquery-ui-bootstrap/extra.html#font-awesome). 

One additional problem why I wrote my original suggestion here was the problem that [Font Awesome](http://fortawesome.github.com/Font-Awesome/) don't provide **full set** of all jQuery UI icons. I posted for example [the new icon request](https://github.com/FortAwesome/Font-Awesome/issues/645) which was unanswered.

I find the idea of your project (jQuery UI Bootstrap) and the idea of Font Awesome very interesting and very helpful. The only problem is that jQuery UI Bootstrap uses raster icons based of PNG files and Font Awesome has another priority in the choice of new icons. How one can see from [the post](http://fortawesome.github.com/Font-Awesome/#contribute) creating of new _vector_ icons with respect of tools like Adobe Illustrator seems be not so complex. It would be very good if you consider in the future to provide full set of scalable jQuery UI icons as the part of jQuery UI Bootstrap Theme. It would makes the jQuery UI Bootstrap more attractive and more helpful. In the case jQuery UI Bootstrap could be _the first_ jQuery UI Theme with the feature.

Best regards
Oleg

**Comment by gtraxx** [comment]
Hi, OlegKi,

> I have to mention that one need change a little the value of margin-left for the icons on the page. 

Could you send me a screenshot for changing the margin (with any browser + OS)

For the moment "are awesome" is supported and can be used instead of PNG icons but there is small problem identified, which requires a modification of the CSS (see the last lines of CSS jquery ui bootstrap, j 'I wrote a note + tips).

In future versions, png icons are removed and replaced with vector (vector font).
I analyze the possibilities.

Best regards :)

**Comment by OlegKi** [comment]
Hi Gerits,

on my Windows 7 computer [the page](http://addyosmani.github.com/jquery-ui-bootstrap/extra.html#font-awesome) displays

<img alt="chrome" src="http://www.ok-soft-gmbh.com/jqGrid/FortAwesome/jquery-ui-bootstrap-chrome.png" />

in Chrome v.24 and in IE9 as

<img alt="chrome" src="http://www.ok-soft-gmbh.com/jqGrid/FortAwesome/jquery-ui-bootstrap-ie9.png" />

I used 300% scaling in both cases to show more clear the problem.

I's very good news that you plan in the future replace all png icons to vector font.

Best regards
Oleg

**Comment by gtraxx** [comment]
ok I'll check and fix bug :)

**Comment by addyosmani** [comment]
Is this good to close?

**Comment by gtraxx** [comment]
I need to replace the UI icons with Font awesome.
I progressing well but I check if all the icons are available ;)

**Comment by addyosmani** [comment]
Cool. Let me know if you need any help. I remember us running into some issues with margin before.

**Comment by gtraxx** [comment]
I expect that the icons are all available
Tests with "Font Awesome" function but it lacks icons

**Comment by OlegKi** [comment]
Probably it was an misunderstanding at the beginning. If I would found _all_ vector icons which I need for jQuery UI in the list of [all icons](http://fortawesome.github.io/Font-Awesome/#all-icons) which already provides "Font Awesome" I would solve the problem myself. Tree months before I posted [small feature request](https://github.com/FortAwesome/Font-Awesome/issues/645) to Font-Awesome about one simple icon which I needed mostly, but the request are still unanswered.

If I understand the problem correctly, the creating of vector icons is not so complex if one uses corresponding tools (see "Contribute Icons to Font Awesome" part [here](http://fortawesome.github.io/Font-Awesome/) where it's described the usage of Adobe Illustrator). What Font-Awesome use is mostly web font in format woff, eot or ttf (see [here](https://github.com/FortAwesome/Font-Awesome/blob/master/css/font-awesome.css) how it do Font-Awesome and [here](http://dev.w3.org/csswg/css-fonts/#src-desc) full possibilities of CSS3). There are exist different free tools additionally which allows to convert one vector font to another format (see [here](http://www.font2web.com/) as an example). WOFF is probably the most important format (see [here](http://caniuse.com/woff) which web browsers supports it).

I see only advantages in the usage of vector web fonts as icons instead of PNG icons. Probably there are some small performance disadvantages in usage of it in old web browsers, but I can't see any visible performance problems in my tests.

So TODOs from the issue which I posted can be divided it two parts:
1. creating some icons which are part of jQuery UI standard Icon list and which are not yet in FortAwesome or on other free web sources
2. usage of the icons directly in jQuery UI 

Probably one can start with the step 2 and with the usage only existing icons which exists now, but I am not sure that look of the mix of icons made in different style will be good.

Thanks for your time,
Oleg
P.S. By the way there are other free web fonts which provide icons (see [here](http://www.entypo.com/, [here]%28http://fontello.com/%29, [here]%28http://icomoon.io/app/%29, [here]%28http://shoestrap.org/downloads/elusive-icons-webfont/%29 and so on)

**Comment by OlegKi** [comment]
Probably the [Font Custom](http://fontcustom.com/) tool (see on [github](https://github.com/FontCustom/fontcustom/) also) could help with the implementation. By the way I posted [the question](http://stackoverflow.com/questions/16102489/usage-of-vector-icons-as-web-fonts-instead-of-png-in-jquery-ui-css-framework) on the stackoverflow and [the request](http://forum.jquery.com/topic/is-it-time-to-replace-png-icons-of-jquery-ui-css-framework-with-vector-based-web-fonts) on the jQuery UI forum, but till now without any progress which could forward to a solution.

**Comment by gtraxx** [comment]
Font Awesome to add additional icons, I check if I have everything you need for integration instead of png icons.

I propose a test version before sending on github

:D
