### ISSUE TITLE
[feedback] buttons

### ISSUE THREAD

**Issue by ThisIsMissEm** [jquery-ui-bootstrap/jquery-ui-bootstrap#13]
I've noted that not all buttons use the animation on the styles, like the download buttons do. The text of buttons is also selectable, which for a UI component doesn't seem like a great idea.

**Comment by beverloo** [comment]
I'd like to add to this that the buttons don't seem to have a pressed state (using Chrome).

**Comment by javajack** [comment]
Better be let's inherit bootstrap 2.0 button styles :)

**Comment by addyosmani** [comment]
@beverloo @miksago 

Thanks for the feedback. I'm going to target adding both the pressed states and animations to the buttons for either 1.5 or 2.0

With respect to the text being selectable, there appear to be quite a few places allowing this (including GitHub) but I could be wrong. Does anyone else feel text on buttons shouldn't be selectable?

**Comment by javajack** [comment]
Does anyone else feel text on buttons shouldn't be selectable? +1 , yes , text being selected on a button is a big turn off in UX !

**Comment by addyosmani** [comment]
I'm on the fence, but if we did opt for this, thoughts on this for the solution?:

Modern browsers:

```
-webkit-user-select: none;
-khtml-user-select: none;
-moz-user-select: none;
-ms-user-select: none;
-o-user-select: none; /*not yet implemented tthomk*/
user-select: none;
```

with the `unselectable` expando attribute of the element being used for IE and Opera.

i.e

```
unselectable="on" 
```

**Comment by tnorthcutt** [comment]
@javajack @miksago can you go into more detail on why you think button text shouldn't be selectable?

**Comment by ThisIsMissEm** [comment]
@tnorthcutt so, if you have a look at any native application, be it on desktop or mobile platforms, the buttons can't have their text selected. Eg, when selecting the text within the application (say a simple note pad app), then you wouldn't expect to select the text of the "save" button, because that's not what you're editing. It just seems strange.

**Comment by addyosmani** [comment]
@miksago that's cool. I'm happy to move ahead with no text selectable, but I think we need to consider how this applies to components other than buttons. If the text cant be selected on buttons does that also suggest text should not be selectable on tabs, accordions etc too?

**Comment by tnorthcutt** [comment]
@miksago That makes sense. However, I believe it's ok for things on the web to be different. I expect text on a website to be text (not an image) and to act like text (be selectable, for one thing). Not only do I expect that, but I believe it to be 'proper' or 'correct'.

**Comment by tanqhnguyen** [comment]
I have just noticed that the buttons do not have pressed state like those using bootstrap, is it gonna be added in the future ? Because I think that the UX would be improved if people can see some changes (even if it is very small) when clicking on buttons.

**Comment by addyosmani** [comment]
@laoshanlung @beverloo previously mentioned this issue and it's going to be tackled in the next few weeks before we hit 1.0. I'm currently fleshing out the third party components we're going to support over the next week but this is definitely on my radar.

**Comment by devinus** [comment]
Regarding buttons having selectable text, since this is supposed to be modeled after Bootstrap it should do what Bootstrap does. Bootstrap does have selectable button text.
