### ISSUE TITLE
Bootstrap 3.0 Compatibility

### ISSUE THREAD

**Issue by Alphonse123** [jquery-ui-bootstrap/jquery-ui-bootstrap#130]
Upcoming changes listed here: https://github.com/twitter/bootstrap/wiki/Upcoming-3.0-changes

**Comment by addyosmani** [comment]
Thanks for the heads up @Alphonse123. I think it's really useful for us to keep an eye on when 3.0 is likely to get released so we can try to wrap up parity with 2.0 well before that. I'll keep this open to track changes post 2.x releases are made on our end.

**Comment by gtraxx** [comment]
Must wait for a stable release of Bootstrap 3.0, see the changes to prepare the work :)

**Comment by rickmills** [comment]
Given that 3.0.0 is now in RC1, will jquery-ui-bootstrap be updated for version 3 now, as they are pushing forward with 3 pretty quickly, making it clear 2.x is no longer going to be used or recommended.

Cheers!

**Comment by gtraxx** [comment]
Hi, @rmwebs, I start working with Bootstrap 3 ;)

**Comment by rickmills** [comment]
Sweet - please do let us know when its ready for testing :)

**Comment by ravimallya** [comment]
+1 we are waiting...

**Comment by gtraxx** [comment]
Bootstrap 3 version is available in branch : https://github.com/addyosmani/jquery-ui-bootstrap/tree/masterbs3

:)

**Comment by gtraxx** [comment]
it's fixed with masterbs3 :)
