### ISSUE TITLE
Next version with Update jQuery UI 1.10

### ISSUE THREAD

**Issue by gtraxx** [jquery-ui-bootstrap/jquery-ui-bootstrap#133]
@addyosmani 

Hello everyone, I started updating jquery ui to 1.10.
For this new version, the documentation will be completely changed for highlighting demonstration.

Should set the version number for this update and also provide for the adaptation bootstrap 3.
I work on this new version and I will send soon :)
PS: Sorry for the delay ;)

Aurélien

**Comment by addyosmani** [comment]
Thanks for the update @gtraxx! I'm currently working on trying to get a few more people
involved in the project to help us get the next version out. 

Maybe we should update the release list to include a list of what we now need to get done
for this and include a link to this issue too?

**Comment by gtraxx** [comment]
We should have people working on version LESS and SASS.
And also to create new image for documentation (Image header): D

**Comment by addyosmani** [comment]
I can do the header (need to remind myself to!) but do you think switching over to using
SASS would make sense for this release? The last time I looked into it it seemed like a
lot of work.

How long do you think it might take to get done?

**Comment by gtraxx** [comment]
I do not know much SASS so I do not know for the moment but it is a good idea

**Comment by addyosmani** [comment]
Maybe I'll try speaking to some designers and we can get a better idea about the time it might take.

**Comment by addyosmani** [comment]
@gtraxx Do you think we could update the readme with the current state of the project? i.e what version of jQuery UI we support, maybe point people to our release thread so they know what the current state of the project is?

**Comment by gtraxx** [comment]
Hi @addyosmani ,
I'm working on the new version + new documentation :)
But what version number should be added? (0.23 => 1.10)
I propose a version number that jQuery UI (Official) :)
Currently,
I work locally but I will send changes to my fork to not overwrite the current version. 
I send changes tonight on my fork, to see the progress

**Comment by addyosmani** [comment]
That is fantastic to hear :)

Because we're still pre-release on the next 'official' version, how about we go for 0.5
for the next version given the amount of work done so far and when we make an official
project release (most major bugs fixed) we'll match the jQuery UI version? :)

That hopefully won't be too long off!

**Comment by gtraxx** [comment]
@addyosmani  Here is a screenshot of the new version under development :)
The documentation uses jQuery UI bootstrap.

![screenshot-new-ui-bootstrap](https://f.cloud.github.com/assets/356674/88134/4b0228c6-64df-11e2-9d9b-b5655a4eeaa3.png)

**Comment by addyosmani** [comment]
Amazing start :) Looks exactly like what I was hoping for! Great work

On Tuesday, January 22, 2013, Gerits aurelien wrote:

> @addyosmani https://github.com/addyosmani Here is a screenshot of the
> new version under development :)
> The documentation uses jQuery UI bootstrap.
> 
> [image: screenshot-new-ui-bootstrap]https://f.cloud.github.com/assets/356674/88134/4b0228c6-64df-11e2-9d9b-b5655a4eeaa3.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/addyosmani/jquery-ui-bootstrap/issues/133#issuecomment-12569384.

## 

_Addy Osmani_

Developer Programs Engineer at Google
Blogger at: http://addyosmani.com
Phone: +44 7771 334170

**Comment by gtraxx** [comment]
A screenshot of a demo for button + button set :D 

![screenshot-new-ui-button](https://f.cloud.github.com/assets/356674/88159/bd7ee44c-64e0-11e2-99be-8db13e92b656.png)

To see the changes: https://github.com/gtraxx/jquery-ui-bootstrap

I sent when everything is finished but I'll fast forward

**Comment by addyosmani** [comment]
Woot! +1 for those example snippets below each group. Great idea.

**Comment by gtraxx** [comment]
Hi @addyosmani , 
I work in the new version of jQuery UI Bootstrap with jQuery 1.9.0 and jQuery UI 1.10.0 but is it possible to send me a compatible version of Wijmo to create the menu in the demo?
Version 1.5 does not work well with jQuery 1.9.0.

I use jquery-migrate for the script to work

Without "jQuery Migrate" script returns the error:

> TypeError: a.browser is undefined (jquery.wijmo-open.1.5.0.min.js)

With "jQuery Migrate" script returns the message :

> JQMIGRATE: jQuery.browser is deprecated (jquery.wijmo-open.1.5.0.min.js)

PS : I added Font-Awesome in the doc :D

**Comment by addyosmani** [comment]
What's the current status of our Wijmo issues? I can ask someone from that team to help if we need it :)

**Comment by gtraxx** [comment]
Hi Addy,
Yes an update to wijmo is necessary

**Comment by addyosmani** [comment]
cc @banzor

**Comment by Heliosmaster** [comment]
Is this issue still actual?

**Comment by gtraxx** [comment]
Yes, but not news of wijmo

**Comment by Heliosmaster** [comment]
Maybe a more appropriate issue can be opened? Technically this refers to jQuery UI 1.10 and the changes that are already implemented in the current tree.

**Comment by gtraxx** [comment]
I close this ticket, you can create a new future for the Advancement of Version :)
