### ISSUE TITLE
shadow missing

### ISSUE THREAD

**Issue by scippio** [jquery-ui-bootstrap/jquery-ui-bootstrap#134]
I think dialog must have shadows like in bootstrap... I think i'ts a bug :)

**Comment by gtraxx** [comment]
I'll check

**Comment by gtraxx** [comment]
Hi,
I added some changes in the new documentation will be available soon.
Dialog boxes are modified to have the shadow Bootstrap :)

Best regards

**Comment by gtraxx** [comment]
Bug fixed (https://github.com/addyosmani/jquery-ui-bootstrap/commit/098b856ad24a0d0c0a2c3556911ff388cf9711ff)

:)
