### ISSUE TITLE
jquery-ui-1.10.0.custom.css overwrites Bootstrap's font color for input boxes

### ISSUE THREAD

**Issue by juristr** [jquery-ui-bootstrap/jquery-ui-bootstrap#143]
In jquery-ui-1.10.0.custom.css there is an entry:

```
input[type="text"],
input[type="password"],
.ui-autocomplete-input,
textarea,
.uneditable-input {
  ...
  color: #808080;
}
```

which overrides Bootstrap's color which is `#555555`.

Here an example of adding a textbox to the jqueryui-bootstrap site (left) and the textbox on the bootstrap site itself (right)

![bootstrap_jqueryui_inputcolor](https://f.cloud.github.com/assets/542458/114280/04db71e0-6b97-11e2-9f56-ecbc77b9c238.png)

How would you fix that? I can provide a pull request if needed.

**Comment by gtraxx** [comment]
Hi juristr,

I'll check :)

**Comment by gtraxx** [comment]
But where do you see the error? Do you have the latest version of the repository ?
![input-2013-01-31](https://f.cloud.github.com/assets/356674/114526/0e8a729c-6ba4-11e2-800f-85b97431542e.png)

**Comment by juristr** [comment]
argh...accidentally deleted my previous reply.

Actually I just downloaded the latest version from the GitHub repo and the problem persists. If you look at the image I attached to this issue you can see the difference in the font color inside input boxes which is because - as mentioned - the jQuery UI bootstrap CSS overwrites Bootstrap's default one (`#555555`) with `#808080`.

If I comment the line from the jQuery bootstrap UI css, then it works. However I noted that the font color is overwritten with (`#808080`) on other places in the CSS as well.

**Comment by gtraxx** [comment]
I think it is ok to use jquery ui bootstrap without bootstrap but I will change the color and find a trick to inherit the bootstrap.
I will make the changes :)

**Comment by juristr** [comment]
perfect, awesome.

## 

_Juri Strumpflohner_
juristr.com
