### ISSUE TITLE
IE 10 blue button from main page look issue. 

### ISSUE THREAD

**Issue by mariuszkochanowski** [jquery-ui-bootstrap/jquery-ui-bootstrap#144]
Blue button  that is visible on main page loses color.
Here http://postimage.org/image/ddqkuvnuz/ you can see how it looks in IE 10.

**Comment by gtraxx** [comment]
Hi arespr, 
do you have a link to a demo of your code ?
The bug is it present in another browser ?
Best regards

**Comment by mariuszkochanowski** [comment]
I opened main page http://addyosmani.github.com/jquery-ui-bootstrap/ in several browsers and i saw that where is issue with blue button "Download stable (v0.5)" in Internet Explorer 10 , then i downloaded source files from github and i opened index.html in IE 10 with the same result - lack of color.

**Comment by gtraxx** [comment]
Hi arespr, 
you need to use the version from the dev repository
Use the latest version :)

**Comment by mariuszkochanowski** [comment]
I have downloaded appropriate version and i noticed that everything looks properly.

**Comment by gtraxx** [comment]
Hi, bug fixed for IE 10 (button primary and button success).
download the current version ;)
Best regards
