### ISSUE TITLE
Range Slider Background Color extending outside component.

### ISSUE THREAD

**Issue by geopii** [jquery-ui-bootstrap/jquery-ui-bootstrap#145]
Using the range slider, when moving the left hand dragging element, the background extends past the right hand element. It also extends outside the component when the right hand element is far enough to the right.

The behaviour is exhibited in Chrome and Firefox but not IE.  It looks like it's connected to the animation of the slider but I've been unable to disable this using animate:false in the slider parameters

![slider-range-bug](https://f.cloud.github.com/assets/954098/135070/35f55708-710c-11e2-9c7e-a715a7894a1a.png)

**Comment by gtraxx** [comment]
Hi geopii, Do you use the latest version (dev in repository) ?

**Comment by geopii** [comment]
Apologies, my mistake– I just got the latest.

**Comment by gtraxx** [comment]
no probleme ;)
