### ISSUE TITLE
Include license information in the readme text

### ISSUE THREAD

**Issue by viruthagiri** [jquery-ui-bootstrap/jquery-ui-bootstrap#146]
Hi, I can't find any license information. Can you include it in the readme file?

**Comment by gtraxx** [comment]
Hi, I do not have license information but I ask Addy thanks
@addyosmani

**Comment by addyosmani** [comment]
MIT. Let's link to http://mit-license.org/ :)

**Comment by gtraxx** [comment]
I add the license, thanks ;)

**Comment by viruthagiri** [comment]
cool :)
