### ISSUE TITLE
un-minified version of jQuery UI

### ISSUE THREAD

**Issue by Spir** [jquery-ui-bootstrap/jquery-ui-bootstrap#147]
Feature request: Can you guys also provide not minified version of jQuery (especially jQuery UI since it's a custom made and there is no possibility to get the un-minified version somewhere online)?

**Comment by gtraxx** [comment]
Hi, 
you want a compressed version of the CSS ?
The js files are minified version (jquery, jquery ui, bootstrap)
Best regards

**Comment by Spir** [comment]
I was wondering if you can provide an uncompressed version of the JS (especially for the jQuery UI JS file) since I can not find an uncompressed version of this file online since it's a custom made.
I need it because my minifier break the already compressed file.
I did a workaround using http://jsbeautifier.org/ and then changed some code so it won't break.
There is at some point this (in a for loop) + ++n which become +++n when minified with all my other file so I did have to changed it to +(++n)
Regards

**Comment by gtraxx** [comment]
uncompressed version online ;)
- jquery ui (no custom)
- Bootstrap without tooltip, popover, button js component (custom)  

view asset/js/src

**Comment by Spir** [comment]
Thanks for your time!

**Comment by gtraxx** [comment]
no problem :)
