### ISSUE TITLE
Icon-only buttons have their icons misaligned in Firefox

### ISSUE THREAD

**Issue by churchofthought** [jquery-ui-bootstrap/jquery-ui-bootstrap#148]
Chrome is fine, FF is misaligned. Not sure what the issue is. CSS looks spot on for the icons, margin-left: -8px, left: 50%, width: 16px. If you can figure it out I'd much appreciate it.

Screenshot here: http://cl.ly/image/1V043f002513

**Comment by gtraxx** [comment]
Hi, ok I'll fix

**Comment by churchofthought** [comment]
Thanks, can you let me know what the issue was when you figure it out? I took a brief stab at it last night but was perplexed.

**Comment by gtraxx** [comment]
Bug is fixed :)

![bug-icon-only-ff](https://f.cloud.github.com/assets/356674/195634/83ae5e8a-7ff9-11e2-8983-93d101b604f6.png)

**Comment by churchofthought** [comment]
Great thank you!

**Comment by addyosmani** [comment]
Thank you, @gtraxx!

**Comment by gtraxx** [comment]
No probleme Addy ;)
