### ISSUE TITLE
Split button difference

### ISSUE THREAD

**Issue by sindresorhus** [jquery-ui-bootstrap/jquery-ui-bootstrap#149]
This split button differers in many ways from the Bootstrap one. jQUI is the first one.

![Screen Shot 2013-02-23 at 20 57 18](https://f.cloud.github.com/assets/170270/188528/61644ea0-7df3-11e2-87fe-b51a55cdd823.png)
![Screen Shot 2013-02-23 at 20 58 13](https://f.cloud.github.com/assets/170270/188529/6179bc2c-7df3-11e2-8463-35bf163df36d.png)

Difference from the original:
- Selection color
- Selection border radius
- No split button active state when the dropdown is visible
- Dropdown is opening in the wrong place
- Clicking the split button when the dropdown is open does not close it

**Comment by gtraxx** [comment]
Hi,
I'm working on a change to have a resemblance :)

**Comment by Heliosmaster** [comment]
Also probably the text should be bold

**Comment by addyosmani** [comment]
+1. We probably want to keep this as similar as possible.

Side: also need to decide at some point if we're going to offer something
for Bootstrap 3.0. Some relatively large visual changes there but it would
be nice for us to maintain something 2.x compat for now for sure.

On Thursday, April 11, 2013, Davide Taviani wrote:

> Also probably the text should be bold
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/addyosmani/jquery-ui-bootstrap/issues/149#issuecomment-16234164
> .

## 

_Addy Osmani_

Developer Programs Engineer at Google
Blogger at: http://addyosmani.com
Phone: +44 7771 334170

**Comment by sindresorhus** [comment]
Not fixed at all. The split button is still completely different from the bootstrap one.

**Comment by Heliosmaster** [comment]
Uhm, curious. I was under the impression that Bootstrap had the focused elements in boldface (as from the previous screenshot), while it does not seem the case 
![Components Bootstrap - Google Chrome_003](https://f.cloud.github.com/assets/283733/390480/2c1e407a-a742-11e2-808e-eee97080a862.png)

So, probably https://github.com/addyosmani/jquery-ui-bootstrap/commit/9066bea4dfe43ca71f7be6736da1659682ddc723 is to be reverted 

Nevertheless it seems that the current behaviour is consistent with the jQuery UI split button: http://jqueryui.com/button/#splitbutton
