### ISSUE TITLE
jQuery autocomplete combobox doesn't look good

### ISSUE THREAD

**Issue by bentzy** [jquery-ui-bootstrap/jquery-ui-bootstrap#150]
Hi! Love your project! Keep it up! :)

I wanted to use the jQuery autocomplete with a combobox and it works good - the only problem is it looks like this:

![image](https://f.cloud.github.com/assets/1738201/197172/731934fc-8033-11e2-8251-e85d3efe6130.png)

Can you reproduce it? Or it's only me? :)

**Comment by gtraxx** [comment]
Hi, do you have an online demo so I can see the problem ?

**Comment by bentzy** [comment]
Ok added some CSS and now it looks like this:
![image](https://f.cloud.github.com/assets/1738201/200153/f20bd2ce-80ba-11e2-9551-4e3250ebeccf.png)

Here is an online demo - but without your JS library:
http://jsfiddle.net/QDeeE/

I copied it from jQuery UI website.

Thanks!!

**Comment by bentzy** [comment]
I changed the CSS and it looks really good now:

.ui-combobox {
    position: relative;
    display: inline-block;
}

.ui-combobox-toggle {
    position: absolute;
    top: 0;
    bottom: 0;
    margin-left: -2px;
    padding-left: 18px;
    padding-top: 8px;
    width: 10px;
    height: 12px;
    /\* support: IE7 */ *height : 1.7em;
    *top: 0.1em;
    *height: 1.7em
}

.ui-combobox-input {
    margin: 0;
    padding: 0.3em;
    width: 300px;
}

Sorry to bother you.
Thanks for helping!!

**Comment by gtraxx** [comment]
Thank you, I'll take your example for demo

Best regards

**Comment by Heliosmaster** [comment]
:+1: to add this to jquery-ui-bootstrap

**Comment by gtraxx** [comment]
I joined right now ;)
