### ISSUE TITLE
jquery-ui-bootstrap Extra(File Input) issues

### ISSUE THREAD

**Issue by wangsong** [jquery-ui-bootstrap/jquery-ui-bootstrap#152]
When i select a file.File name and icon overlap.
![ ](https://f.cloud.github.com/assets/1917017/203795/2fd39c02-8149-11e2-9b74-4538893f02f0.jpg)
Add this css[padding-left: 25px;].This should resolve the problem.
![image](https://f.cloud.github.com/assets/1917017/203807/ff901a38-8149-11e2-8597-d1628307e29f.png)

**Comment by gtraxx** [comment]
Bug is fixed :)
Thanks
