### ISSUE TITLE
Integrate jQuery UI menubar

### ISSUE THREAD

**Issue by dswarbrick** [jquery-ui-bootstrap/jquery-ui-bootstrap#153]
I've been using a custom jQuery UI build from the menubar branch for over a year now, with no noticeable bugs.

Have you guys considered integrating menubar, instead of (or as an alternative to) the Wijmo menu?

**Comment by gtraxx** [comment]
Hi,
Do you have a link to menubar ?
It is part of the official branches of jQuery UI (I do not remember)
Wijmo has not been updated, I expect a response from the team

Thanks :)

**Comment by dswarbrick** [comment]
It's an official branch - https://github.com/jquery/jquery-ui/tree/menubar - the branch hasn't been worked on a for a while, however a clone of the menubar branch can still merge master cleanly. I'm using this method to do a custom build of it for my projects. The menubar stuff shares a lot of code with selectmenu.

**Comment by gtraxx** [comment]
ok I'll see if menubar is compatible with jQuery UI 1.10.1 and adjusted as necessary :)

**Comment by keithlea** [comment]
Any update?

**Comment by purtuga** [comment]
I'm also interested in this... I have been using menubar for over a year now as well with no major issues...
