### ISSUE TITLE
jQgrid: selection doesn't work in IE9

### ISSUE THREAD

**Issue by Leftyx** [jquery-ui-bootstrap/jquery-ui-bootstrap#154]
IE9 doesn't keep selection when row is actually selected.

**Comment by gtraxx** [comment]
Hi Leftyx,
@addyosmani and @basejump have worked on jqGrid
See if this is a bug from the skin or jqGrid

Thanks :)

**Comment by Leftyx** [comment]
Hi gtraxx,

I've downloaded the latest updates and I can confirm it doesn't work properly.
it seems that it only works for rows with class = ui-priority-secondary.

thanks.

**Comment by basejump** [comment]
its not a bug in jqGrid as their site is fine in ie9
jqGrid.overrides.css will need to be tweaked. As usual its always IE weirdness. 
Please share your changes if you figure it out.

**Comment by Leftyx** [comment]
I've managed to find a solution adding 

background-image: -ms-linear-gradient(top, #FCEEC1, #EEDC94); 

to the class:

.ui-jqgrid-btable .ui-widget-content.ui-state-highlight {

}
