### ISSUE TITLE
suggestion about bundling

### ISSUE THREAD

**Issue by bealtine** [jquery-ui-bootstrap/jquery-ui-bootstrap#155]
This is merely a suggestion...

I would suggest you bundle your distro like this:

assets
assets->bootstrap
assets->jqueryuicustom

That way I can just update each branch as required, harder to type but easier to maintain

**Comment by gtraxx** [comment]
I prefer to rename the folder
css-> custom-theme
in
css-> ui-bootstrap
To have a similar architecture with jQuery UI
The assets folder contains the documentation and demos
Thanks for the suggestion ;)

**Comment by addyosmani** [comment]
I like the suggestion @gtraxx. We've had some issues come in about improving our install instructions so maybe this could be done as part of a clean-up.

**Comment by bealtine** [comment]
Well the reason I suggested it was that I decided to update bootstrap so I moved everything to the layout I suggested and just unzipped the new bootstrap distro (due to bugs in the bootstrap distro supplied) into the dir and off I went:) No problems noticed and the problems I was having were fixed. If I went with the standard jqueryui distro  layout I'd have to unzip one file here and a different file there. Not a big thing but it made my life easier:)

**Comment by Heliosmaster** [comment]
:+1: on the cleanup / renaming of assets

**Comment by gtraxx** [comment]
What do you think @addyosmani 
It's Addy the boss lol
