### ISSUE TITLE
After Downloading

### ISSUE THREAD

**Issue by ghost** [jquery-ui-bootstrap/jquery-ui-bootstrap#157]
After I downloaded the "stable version" are they talking about changing the custom-theme in the css folder? If I change that I then add the js and css folders in their? What files are needed within that?

Is there a way I can just add the jquery version to the twitter bootstrap folder or do I have to do it this way?

**Comment by neverfox** [comment]
I too found the instructions confusing. I'm not exactly sure what I'm supposed to do once I download this and what files are necessary to take from the archive to replace what I have with default bootstrap and jquery-ui. The instructions show some sort of interactive GUI where features are selected for a custom mix but where is that found?

Am I supposed to replace my js files for bootstrap and jquery-ui with these or just the css?

**Comment by Heliosmaster** [comment]
After you download the .zip file, unzip it and in the css folder you will find a "custom-theme" folder.

That's the one you have to put in the "css" folder of your project, and that's it.

Include the .css file inside your project (for me it was `link{:href=>"/css/custom-theme/jquery-ui-1.10.0.custom.css", :rel => "stylesheet", :media => "screen"}`) and you are done.

**Comment by addyosmani** [comment]
Thanks for highlighting this issue. It's clear that we need to improve the installation instructions to make it as easy as possible to get started. Do you feel the changes from @Heliosmaster (thanks!) make the workflow clearer? Let me know if it's still confusing and we'll rework the homepage.

**Comment by gtraxx** [comment]
Thank you for the information, 
@addyosmani 
sorry for the delay but I've been sick all week :)
I shall return it immediately ;)

**Comment by helgator** [comment]
Thank you for this project but there is still no usable instruction on how to use jquery-ui-bootstrap. Just including the css is definitely not sufficient. At first one needs to specify what elements should be included, like Tooltips. But there is nowhere written how to find that GUI with the checkboxes to do exactly that. So IMHO the usage instruction need a decent review. thx

**Comment by gtraxx** [comment]
@helgator 
Hi,
jQuery UI Bootstrap, respects the rules applied in Twitter Bootstrap but with the use of jQuery UI.
This is a theme completely redesigned to be close to Bootstrap, documentation is updated regularly to match user expectations, missing information, you can specify.

**Comment by helgator** [comment]
Hi, missing information: how to find that GUI with the checkboxes to do the customisation

**Comment by Heliosmaster** [comment]
You mean this GUI? http://twitter.github.com/bootstrap/customize.html

That's Bootstrap, not jQuery UI Bootstrap. This is a theme.

(still some clarification on why those images are there, might be good :smile:  )

**Comment by helgator** [comment]
Thanks, I know your link is Bootstrap but where is that GUI for jquery-ui-bootstrap? I need to exclude the tool tips because they collide with my bootstrap files.
And a general question: when I link to the jquery-ui-bootstrap files I see that they are included correctly, but no component picks up the bootstrap style. I have a themeable calendar and a file manager but I cant figure out how to convince those to take on the bootstrap styles.

**Comment by helgator** [comment]
Hi, there is still the same instruction: "Select custom jQuery UI components (eg exclude tooltip) ". But when I try to select the components via the checkboxes underneath the instruction it is revealed that those checkboxes are images. So still the same confusion - where do I find these checkboxes in real?
