### ISSUE TITLE
Menu: Submenu open overlap (v. 1.10.1)

### ISSUE THREAD

**Issue by pdorgambide** [jquery-ui-bootstrap/jquery-ui-bootstrap#160]
First of all: 
Great Job !!! 

The UI Menu don't open properly the submenus and don't disable the state with ui-state-disabled. This issue was checked into your webpage.
![Components in jQuery UI Bootstrap - Google Chrome_2013-03-16_11-50-03](https://f.cloud.github.com/assets/2659125/266687/5eaa8848-8e27-11e2-9aaf-81eeb5ce3f25.png)

Sorry for my pour english, best regards and congratulations for your great job.

**Comment by addyosmani** [comment]
Thank you for reporting this. We will do our best to get this addressed as long as we can reproduce it.

**Comment by Heliosmaster** [comment]
I see the same behaviour in here: http://addyosmani.github.com/jquery-ui-bootstrap/components.html#block-menu

Hovering with the mouse over Salzburg it opens the submenu with Delphi and if you move again opens up again its submenu producing the visual result of the screenshot of @pdorgambide 

Maybe the submenus could open on the right of the parent menu? (amazon-like)

**Comment by pdorgambide** [comment]
Hello:
I detect that with FireFox the menu works fine, the wrong behavior was happened with Chrome.(version 25.0.1364.172). 
I hope that this could help you.

**Comment by gtraxx** [comment]
I found, I send the change

**Comment by gtraxx** [comment]
Sorry for the revert, I did not use my account
It is sent ;)
