### ISSUE TITLE
On datepicker, today is not highlighted

### ISSUE THREAD

**Issue by camilosw** [jquery-ui-bootstrap/jquery-ui-bootstrap#170]
On the datepicker, current day has the class ui-state-highlight but it's not highlighted. 

On jquery ui css, the Interaction Cues styles are after datepicker styles, but you have this before datepicker styles. Due to this changed order, ui-state-default override ui-state-highlight.

This bug is related with #114.

**Comment by gtraxx** [comment]
Could you make a screenshot so that I can identify the problem.
I'm highlighting with FF
![datepicker-highlight](https://f.cloud.github.com/assets/356674/389905/79129f7a-a729-11e2-94ac-ed95d1660c4e.png)

**Comment by Heliosmaster** [comment]
I also can't reproduce the problem. I have both tried in the jQueri-UI page and in a web application of mine that uses the theme, and in both cases the current day was highlighted.

**Comment by camilosw** [comment]
This is a comparison with the datepicker on the jquery ui site

![datepicker](https://f.cloud.github.com/assets/1142037/391330/939cd110-a762-11e2-959b-3bad186c9732.png)

As you can see, on jquery ui bootstrap today is not highlighted.

**Comment by gtraxx** [comment]
Bug is fixed :)

**Comment by luchopintado** [comment]
Try this code: 

```
$('#datepicker')
.datepicker({
    todayHighlight: true,
    ...
})
```

**Comment by appsmarina** [comment]
Thanks luchopintado

**Comment by iraklisg** [comment]
thanks @luchopintado, that did the trick for me as well

**Comment by tobodioya** [comment]
Thanks @luchopintado. That was helpful

**Comment by iamarsingh** [comment]
Thanks @luchopintado Code is fine but after this code picker is closing on selecting date
