### ISSUE TITLE
Repository Cleanup + Proposal

### ISSUE THREAD

**Issue by Heliosmaster** [jquery-ui-bootstrap/jquery-ui-bootstrap#171]
Pretty code thrives with a tidy repository. Despite the fact that the things that I am about to mention are not essential for the project, I still believe that would be useful, improving both the usability and the development process. 

Please keep in mind that I came to know jQuery-UI Bootstrap not a long time ago, and until a few days ago I was not interested in it as a repository, but only as a tool.

Sorry If I am being too bold, but I think that GitHub issues are a nice place also for these kinds of discussions. I noticed some of these topics around in many issues (as side comments, or something like that), and I thought to include some of them in a more comprehensive list.

To @addyosmani  and @gtraxx : think about the following topics as a potential TODO list in my humble opinion :smile:  As I believe to be not that good in "making" (I fixed a couple of bugs, but nothing fancy) I thought about giving my contribution with a little of (tentative) reorganization.
### Versioning

I can see from both tags and the homepage that the version should be v0.5 (pre final?). I am afraid that it does not tell much (I can find v0.25, but is that older than 0.5? was it supposed to be something like v0.2.5 ?). As with everything, a clear versioning system helps the user to identify when he should upgrade and what to expect.

If I remember correctly, I saw a proposal about moving to the same numbering of Bootstrap. In my opinion it makes a lot of sense, so people know what to expect.

But similarly, we depend (largely) on jQuery UI. 

My proposal is to use  **vX.Y.Z**
- X denotes the version of Bootstrap we are going to address (only one digit because by definition, minor releases do not differ THAT much, and we as a theme that aims to recreate its experience, should ideally not even feel the difference between them)
- Y is increased whenever we make significant changes (add a new third-party widget)
- Z whenever we fix a bug that alters the visual behaviour (we might even not care about this point)

The tagging should still be done by tags.
### Branches

At this time, there are 5 branches, _master_, _bootstrap1.9_, _bootstrap2-dev_, _bootstrap2-addy_, _gh-pages_. Of these 5, only the last one is updated and functional.

My proposal is to delete everything but _gh-pages_, as that's the one that can be accessed with the url (through Github Pages). Definitely keeping a _develop_ branch can be useful (and it will indeed when we will try to look at Bootstrap 3.0), but in general we should not have that many branches lying around. Let's do as good gardeners and prune!
### Issues

Some issues can be closed imho: #129 #86 
In general we should look again at almost all of them (as some are a year old, and not addressed), and start closing them, doing also proper re-tagging.

The idea is that Bootstrap 3.0 is not that far, and considering that we will not have very quickly an update of jQuery UI, we should at least have a robust 2.x compatibility.
### Usability improvements

More or less as suggested in #155, but maybe being a little more thorough, along with looking again at the installation instructions. My idea is that providing the compressed package through GitHub (as is now) + renaming the assets (including the version) would already improve the installation.

**Comment by gtraxx** [comment]
Thank you for the suggestions :)

I asked Addy to the version numbering, we do not have to decide.

Follow the numbering of jQuery UI will be a great idea.

we must remove branches and cleaning repository, but also close the old issues.

We will discuss with Addy and see for changes to an organization github.

Thanks

**Comment by Heliosmaster** [comment]
Ok. Also #112 is related (as it cointains an ideal roadmap)

**Comment by boulox** [comment]
Just my 2cents  but following the more widely use standard of Git would be more profitable for the project :

Use master branch, semver versioning, add component.json/package.json  to enable installation by bower and co...

**Comment by Heliosmaster** [comment]
My line of thought is quite similar to semver, if you look carefully at my proposal of X.Y.Z; however, I feel that this project does not fall (technically speaking) into the use case of semver. I just imagine it being more consistent for ruby gems with methods and proper APIs (which lie at the very core of semver), rather than a CSS theme.

Similarly for the branches: I know that the best practice is to have the development into the master branch, but as we are employing Github Pages as the main website (and reference) of the project, using gh-pages seems more convenient. This for the **current** state of the project, imho.

Of course you view jQuery UI Bootstrap simply as a package (I did not know Bower, but I understood that is something similar to Rubygems), we might as well split this repository in two: package and website. Then the website has gh-pages, and the package has master, and the development progresses more in a conventional way.

**Comment by 01iv3r** [comment]
Just to confirm, which branch should I be using with Bootstrap 2.3.1?
gh-pages seems to be the most recently updated, but I'm still seeing the issue with the bouncing range slider.
no idea what's going on here.

**Comment by gtraxx** [comment]
GH-pages is useful to update the documentation, we do not have to do two commits.

I analyze what I move, change to the folder structure :)

**Comment by chicoxyzzy** [comment]
+1
Please switch to semver and drop version in filenames. It is too hard to automate building process right now. I use the whole custom Grunt.js multitask for including jquery-ui-bootstrap into my project.
