### ISSUE TITLE
bower support

### ISSUE THREAD

**Issue by mic0331** [jquery-ui-bootstrap/jquery-ui-bootstrap#174]
Hello,

is there any plan to have this theme available with bower ?
at the moment, only this fork is accessible 

git://github.com/gustavohenke/jquery-ui-bootstrap

Thanks

**Comment by gustavohenke** [comment]
That's not a fork :)

**Comment by gustavohenke** [comment]
Also, @addyosmani's repo is available at **jqueryuibootstrap**.

**Comment by mic0331** [comment]
@gustavohenke thanks and sorry for the fork ;-)
