### ISSUE TITLE
Dialog now showing bootstrap style buttons

### ISSUE THREAD

**Issue by umefarooq** [jquery-ui-bootstrap/jquery-ui-bootstrap#178]
UI Dialog not loading bootstrap style buttons, it always show default buttons what i am doing wrong

**Comment by gtraxx** [comment]
Hi, could you send a screenshot?
Would you have a demo?

Aurelien

**Comment by umefarooq** [comment]
here is screenshot http://imm.io/188hE

**Comment by gtraxx** [comment]
Have you checked your global CSS ?
Do you have a link to see the problem? May be a conflict with your CSS

**Comment by gtraxx** [comment]
Hi, add support in the new version 1.0 alpha

view issue(https://github.com/addyosmani/jquery-ui-bootstrap/issues/202)
