### ISSUE TITLE
Wijmo menu is not working in IE9

### ISSUE THREAD

**Issue by shahnawazk** [jquery-ui-bootstrap/jquery-ui-bootstrap#18]
Wijmo menu is not properly rendered and worked in IE9.

**Comment by addyosmani** [comment]
@shahnawazk could you provide some more details about what isn't working? There's a known styling issue with parent elements that we're working on fixing, but the menus themselves should be sliding out. Is that not happening?

**Comment by shahnawazk** [comment]
I think it's not styled properly [only in IE9] and when I hover them it does nothing but flickering.

Please see this: http://t.co/omOXtvlc

I'm closing both of my issues reported, hope you'll get it to work.

Nice job.

**Comment by addyosmani** [comment]
@shahnawazk thanks for reporting!
