### ISSUE TITLE
scaffolding(Grid), Base CSS in jquery-ui-bootstrap

### ISSUE THREAD

**Issue by ghost** [jquery-ui-bootstrap/jquery-ui-bootstrap#182]
It will be nice to see the scaffolding(Grid), Base CSS in jquery-ui-bootstrap.
http://twitter.github.io/bootstrap/scaffolding.html
http://twitter.github.io/bootstrap/base-css.html

**Comment by sergeyklay** [comment]
+1

**Comment by ghost** [comment]
Sorry, it's my mistake. Scaffolding(Grid) and Base CSS are already in bootstrap.min.css.
