### ISSUE TITLE
Popover Control

### ISSUE THREAD

**Issue by sinvise** [jquery-ui-bootstrap/jquery-ui-bootstrap#183]
Hi

Is it possible to use the bootstrap popover control as found here http://twitter.github.io/bootstrap/javascript.html

most my work is done in jQuery UI but would like the bootstrap popover.

Thanks

**Comment by gtraxx** [comment]
Hi, 
I work on this feature :)

**Comment by sinvise** [comment]
Hi

Does that mean the feature is still in development or it is already included in the jQuery UI Bootstrap package?

Thanks

**Comment by gtraxx** [comment]
jQuery UI does not include this feature, I'll create it with a jQuery UI widget :)
