### ISSUE TITLE
Style doesn't change whit $("#shuffle").button();

### ISSUE THREAD

**Issue by camilosw** [jquery-ui-bootstrap/jquery-ui-bootstrap#184]
On Simple Toolbar, shuffle is a checkbox and it's styled with $("#shuffle").button();

On http://jqueryui.com/button/#checkbox the button style change when I click the control, but on jquery-ui-bootstrap, the style doesn't change.

**JQuery UI**
![screen shot 2013-06-14 at 11 24 16 am](https://f.cloud.github.com/assets/1142037/655268/f3c85440-d50e-11e2-9381-de58f55b42fd.png)
![screen shot 2013-06-14 at 11 24 25 am](https://f.cloud.github.com/assets/1142037/655271/f7c9b098-d50e-11e2-9499-4093b336ad53.png)

**JQuery UI Bootstrap**
![screen shot 2013-06-14 at 11 15 46 am](https://f.cloud.github.com/assets/1142037/655265/e9d6ec62-d50e-11e2-8e03-8e84ae56410e.png)
![screen shot 2013-06-14 at 11 15 55 am](https://f.cloud.github.com/assets/1142037/655266/ee33a926-d50e-11e2-93d2-302909a8aef4.png)

**Comment by phil-w** [comment]
Yeah, you can see that on the demo page right here. If you put your browser debugger on it you'll see that the style for the blue "checked" state comes from the rule:
 .ui-buttonset .ui-state-active 

so you need to apply that style to the "shuffle" button. I'm using ASP.NET checkboxes so the structure for me may be a little different, but just copy the rule for that thing above and put that CSS into a new rule for:
    .ui-button.ui-state-active  
and the job's done.

I don't know how to fix it in the repository here or I'd do that for ya, but it may be different for standard HTML checkboxes anyway.
