### ISSUE TITLE
Move to an organization.

### ISSUE THREAD

**Issue by addyosmani** [jquery-ui-bootstrap/jquery-ui-bootstrap#189]
We (sadly) haven't had the time to properly update this project due to being involved in so many others of late. This is clear looking at the bug tracker.

There's clearly however interest in jQuery UI Bootstrap and offering developers using jQuery UI a slick looking theme that works with Twitter Bootstrap.

If you're interested in contributing to this project, please reply on this thread. If there's enough interest I'll move this to an org and put together a team that we can use to develop it further. 

I'm happy to oversee with @gtraxx

**Comment by gtraxx** [comment]
yes I continue to contribute.
I'll check the remaining issues and make changes :)

**Comment by sergeyklay** [comment]
Good idea! :+1:

**Comment by gtraxx** [comment]
Hi Addy,
When will you transfer the project to an organization ?

**Comment by Johann-S** [comment]
I want to contribute to this good project. :)

**Comment by addyosmani** [comment]
I'm happy to move this project to an org soon. Some things I think we should tackle before that:
- Tag a new release and update the site
- State our intentions with respect to Bootstrap 3. RC1 is now out and people are going to ask when/if this project is going to support it. I think that mentioning this on the homepage somewhere would be a good idea.
- Our site mentions nothing about the total filesize of the project - we probably should. People are going to wonder what the filesize cost is when you consider the theme, overrides, jQuery UI and so on and we should be upfront about it on the homepage.

**Comment by gtraxx** [comment]
Hi, @addyosmani , 
I started the changes with bootstrap 3 RC1

I sent changes for current version, soon the icons are changed to "Font Awesome"
:)

**Comment by dharapvj** [comment]
Hello @addyosmani ,

I do not have a lot of experience in open source contribution world. But better late than never :-)

I would like to continue to contribute to this project.

Also - +1 to bullet points that you mentioned.

@gtraxx - I was actually searching for Bootstrap3 RC1 branch and stumbled across this issue. Could you push the BS3 changes to different branch?

**Comment by dswarbrick** [comment]
Which version of jQuery UI will the upcoming tag be based on? Is there any chance that it could include the menubar from current jQuery UI master branch?

**Comment by gtraxx** [comment]
@dswarbrick
I just added the latest version of jQuery UI menu bar is an extension

@dharapvj 
I'll see to organize the work and clean the old branches
:)

**Comment by dswarbrick** [comment]
@gtraxx I don't see any mention of "menubar" in the current gh-pages branch.... jquery UI has a "menu" component (or selectmenu as it's sometimes referred to), and a "menubar" component - the latter only being in the menubar branch of jquery UI. Although menubar shares a lot of code with menu, it has not yet been merged to master. However, I've been using it in custom builds for almost 2 years now.... (yeah, jquery moves slowly with some things)

**Comment by gtraxx** [comment]
Hi @dswarbrick 
Yes I have confused with jQuery menu but I'll add :)

**Comment by addyosmani** [comment]
We've finally moved to an organization! Closing this issue.

@gtraxx I've just gone through and closed most of the issues to do with the older version of the project. As requested on another thread if you could get setup a new version of the site where we can point folks that would be awesome.
