### ISSUE TITLE
table hover effect missing?

### ISSUE THREAD

**Issue by deostroll** [jquery-ui-bootstrap/jquery-ui-bootstrap#193]
Unable to get the table hover effect as shown in the figure...
![hover](https://f.cloud.github.com/assets/415336/879504/b793247a-f929-11e2-87d7-2ac5bb1aac88.png)

**Comment by gtraxx** [comment]
Hi, 
would you have a demo or script ?

**Comment by deostroll** [comment]
http://jsfiddle.net/deostroll/G5zT8/
