### ISSUE TITLE
Support for indeterminate progress bars

### ISSUE THREAD

**Issue by EHLOVader** [jquery-ui-bootstrap/jquery-ui-bootstrap#194]
I noticed that there isn't any CSS for indeterminate progress bars, and the gif is also omitted.

**Comment by gtraxx** [comment]
Hi, progress bars "ui-progressbar" in css jquery-ui-1.10.3.custom.css

**Comment by EHLOVader** [comment]
That doesn't cover indeterminate progress bars.

For an example of what I mean by indeterminate [here is the demo from jquery-ui directly](http://jqueryui.com/resources/demos/progressbar/indeterminate.html).

Checking their source and comparing, jqueryuibootstrap has all the javascript needed to create the dom for the overlay, however it is missing the styles. And that gif. Still.

The CSS I refer to can be found here.
https://github.com/jquery/jquery-ui/blob/1.10.2/themes/base/jquery.ui.progressbar.css

EDIT: Sorry I should have linked the right branch.

**Comment by gtraxx** [comment]
Hi, I add support in the new version 1.0 alpha
