### ISSUE TITLE
Getting the button css manually?

### ISSUE THREAD

**Issue by deostroll** [jquery-ui-bootstrap/jquery-ui-bootstrap#196]
In classic bootstrap, you can get all the button styles (curvy corners, etc) by simply adding a class (`<button class="btn">Click Me!</button>`)

However, in this library we don't have a simple way of doing it. We'd have to always call the `.button()` on the corresponding element to get the proper button...

It would be great if we can simply use the bootstrap styles out of box...

http://jsfiddle.net/deostroll/KjQwL/

**Comment by gtraxx** [comment]
Hi, You add the class ui-corner-all or used button elements

``` javascript
$('button').button();
```
