### ISSUE TITLE
Bad smell in jquery-ui-bootstrap less file

### ISSUE THREAD

**Issue by ZengII** [jquery-ui-bootstrap/jquery-ui-bootstrap#199]
I feel some bad smell in less file when I try to define some custom variables.
for example,the snippet as below:
+++++++++++++
.ui-state-hover {
    color: @grayDarker;
}
+++++++++++++
if I don't rewrite the original code, I can't define my custom hover color.
Maybe we should have semantic variable name like @uihovercolor to use in the place instead of @grayDarker .

+++++++++++++
another snippet as below:
+++++++++++++
.ui-widget-content {
    background: @white url("@{image-dir}/ui-bg_glass_75_ffffff_1x400.png") 50% 50% repeat-x;
}
+++++++++++++
jquery-ui provide several theme and different theme have some different image name 
Since jquery-ui-bootstrap project use jquery ui theme image as resource,
maybe we can use a variable to repalce "ui-bg_glass_75_ffffff_1x400.png".

Everybody agree these suggestions, or not ?.

**Comment by dharapvj** [comment]
Valid points @ZengII ! Thanks for bring them to my attention.

Let me look at these cases. This is the exact reason why I have created two different themes to weed out such hard-codings if I have left them anywhere.

Planning to add one more completely different theme so that more such issues will be removed.

**Comment by dharapvj** [comment]
@ZengII,

Key issue in the image url is that this project does not create the said background images dynamically - like jquery theme-roller website does. So.. even if I convert the url to use the variable - it will not be generating the required background image automatically. And hence it will create unfortunate HTTP 404s :worried: 

Anyways.. I am thinking of putting in variable enabled version. My only issue at this moment is about how to explain user about 404s.

@addyosmani, @gtraxx  - Any thoughts on how to handle this situation?

**Comment by ZengII** [comment]
Thanks @dharapvj . 
Maybe the explanation can be put in jquery-ui-bootstrap website, and a link guides user to jQuery UI website to download different theme images.
