### ISSUE TITLE
Primary Button

### ISSUE THREAD

**Issue by christopherboss** [jquery-ui-bootstrap/jquery-ui-bootstrap#200]
How exactly do I define the other button classes? It seems that my ui-state-default has to not be a part of the class in order for primary, success, warning and the others go to work properly. Obviously I can remove the class and add the new class to make this work but, I'm unsure if there's an easier way of doing this and I'm just overlooking it.

Thanks in advanced.

**Comment by dharapvj** [comment]
Pardon me if I misread your question.. but.. Shouldn't this be all? you should not "work the CSS" yourself. rather ask JQuery to do that for you...

``` html
<div class="mycontainer">
    <button class="ui-button-primary">Primary</button>
    <button class="ui-button-success">Success</button>
    <button class="ui-button-info">Info</button>
    <button class="ui-button-warning">Warning</button>
    <button class="ui-button-danger">Danger</button>
    <button class="ui-button-inverse">Inverse</button>
</div>
<script>
    $('.mycontainer button').button();
</script>
```

**Comment by christopherboss** [comment]
dharapvj, thank you for the reply.

This doesn't work for me, for whatever reason. This is what I tried to do but, until I remove the ui-state-default class from the element, it will not load any other style.

I'm defining $("button").button(); on the document being ready.

This should apply to all buttons, obviously loaded into the DOM on the document being ready. But defining the class as you did, does nothing for me. I guess this is why I'm confused. I'm doing it correctly, but it appears to not be working appropriately. I'll take another look once home from work and see what I can come up with. Again, thank you for the reply.

**Comment by dharapvj** [comment]
can you create a fiddle on jsfiddle?

**Comment by dharapvj** [comment]
This gives me a perfect bootstrap looking buttons created from JQuery button() command. Just ensure you have 2 css and 2 js files available at appropriate path.

``` html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="css/custom-theme/jquery-ui-1.10.3.custom.css">
</head>
<body>
<div class="mycontainer">
    <button class="ui-button-primary">Primary</button>
    <button class="ui-button-success">Success</button>
    <button class="ui-button-info">Info</button>
    <button class="ui-button-warning">Warning</button>
    <button class="ui-button-danger">Danger</button>
    <button class="ui-button-inverse">Inverse</button>
</div>

<!-- Placed at the end of the document so the pages load faster -->
<script src="assets/js/jquery-1.9.1.min.js"></script>
<script src="assets/js/jquery-ui-1.10.3.custom.min.js"></script>
<script>
    $(function(){
        $('.mycontainer button').button();
    });
</script>
</body>
</html>
```

**Comment by christopherboss** [comment]
Sorry for the delay, I was at work at the time of your replies. I'm going to go ahead and re-download the bootstrap and see if perhaps I downloaded it from the incorrect place.

I'll let you know how it works out.

**Comment by devilized** [comment]
I had the same issue, and found it to be that the parent div of the button had class ui-widget-content. This combined with a child button, which by default has class ui-state-default even when you specify class ui-button-primary, causes the custom button styles to be suppressed. 

To replicate the issue, try this: 

``` html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="css/custom-theme/jquery-ui-1.10.3.custom.css">
</head>
<body>
<div class="mycontainer ui-widget-content">
    <button class="ui-button-primary">Primary</button>
    <button class="ui-button-success">Success</button>
    <button class="ui-button-info">Info</button>
    <button class="ui-button-warning">Warning</button>
    <button class="ui-button-danger">Danger</button>
    <button class="ui-button-inverse">Inverse</button>
</div>

<!-- Placed at the end of the document so the pages load faster -->
<script src="assets/js/jquery-1.9.1.min.js"></script>
<script src="assets/js/jquery-ui-1.10.3.custom.min.js"></script>
<script>
    $(function(){
        $('.mycontainer button').button();
    });
</script>
</body>
</html>

```

**Comment by dharapvj** [comment]
@devilized , @c3vo - I have put a fix and added a testcase for this fix.

@gtraxx - I am not able to create a PR since I have pushed few other commits to my local origin - which are not yet ready to be pushed to upstream. Can you pull the specific commit which is shown above and merge into master? I am still learning the "git way" of doing things. :confounded:

**Comment by gtraxx** [comment]
This issue is fixed ?

**Comment by bqsylou** [comment]
Hello there !
After searching a bit, the change dharapvj proposed isn't included into the lastest version.

Also, in addition to his fix, the hover states is still lost. I propose to add this :

.ui-widget-content .ui-button-primary:hover,
.ui-widget-content .ui-button-success:hover,
.ui-widget-content .ui-button-info:hover,
.ui-widget-content .ui-button-danger:hover,
.ui-widget-content .ui-button-warning:hover,
.ui-widget-content .ui-button-inverse:hover,
.ui-button-primary:hover,
.ui-button-success:hover,
.ui-button-info:hover,
.ui-button-danger:hover, 
.ui-button-warning:hover,
.ui-button-inverse:hover{
    color: #ffffff;
    text-decoration: none;
}

.ui-widget-content .ui-button-primary:hover,
.ui-widget-content .ui-button-primary:focus,
.ui-button-primary:hover,
.ui-button-primary:focus {
    color: #ffffff;
    background-color: #3276b1;
    border-color: #285e8e;
}

.ui-widget-content .ui-button-success:hover,
.ui-button-success:hover{
  color: #ffffff;
  background-color: #47a447;
  border-color: #398439;
}

.ui-widget-content .ui-button-info:hover,
.ui-button-info:hover{
  color: #ffffff;
  background-color: #39b3d7;
  border-color: #269abc;
}

.ui-widget-content .ui-button-danger:hover,
.ui-button-danger:hover{
  color: #ffffff;
  background-color: #d2322d;
  border-color: #ac2925;
}

.ui-widget-content .ui-button-warning:hover,
.ui-button-warning:hover{
    color: #ffffff;
    background-color: #ed9c28;
    border-color: #d58512;
}

.ui-widget-content .ui-button-inverse:hover,
.ui-button-inverse:hover{
    color: #ffffff;
    background-color: #363636;
    border-color: #000000;
}

Regards,
B.
