### ISSUE TITLE
bootstrap 3 is coming

### ISSUE THREAD

**Issue by joodies** [jquery-ui-bootstrap/jquery-ui-bootstrap#201]
will you upgrade to bootstrap 3 ?

**Comment by gtraxx** [comment]
Hi, I start working with bootstrap 3
I will post a beta version :)

**Comment by joodies** [comment]
Very nice to hear that! I'm trying to extend the dialog widget, to add min(dock) and maximum function to it.

**Comment by addyosmani** [comment]
That's fantastic to hear, @gtraxx. Bootstrap RC2 came out this week.

**Comment by dharapvj** [comment]
@gtraxx - The good looking theme of Bootstrap 2 is [now available in Bootstrap 3](https://github.com/twbs/bootstrap/issues/8706#ref-commit-f6c151a)

We might want to use this theme rather than the default theme which is way more barebones.

Btw, Final bootstrap 3 is due for release today/tomorrow. I would appreciate if you could push your WIP content somewhere - may be as a local branch in your user area.

**Comment by gtraxx** [comment]
I  working with bootstrap 3 for the new version, but it would create a version number ( @addyosmani  )

**Comment by fnagel** [comment]
_subscribe_

**Comment by gtraxx** [comment]
Many modification work for compatibility with bootstrap 3, I sent the files once finished.
@addyosmani : What version number for jQuery UI Bootstrap ?
Best regards ;)

**Comment by gtraxx** [comment]
Hello,
Here is a screenshot of my work in jQuery UI bootstrap with Bootstrap 3.

The new version number : 1.0 alpha :D 

![jquery-ui-bootstrap-bs3](https://f.cloud.github.com/assets/356674/1008940/b5d2ad9a-0b30-11e3-890d-b0abdf0aebd2.png)

**Comment by sergiotapia** [comment]
Can't wait! Thank you for working on this.

**Comment by dharapvj** [comment]
+1 @gtraxx - Looks good!

**Comment by gtraxx** [comment]
I used the same method as Bootstrap 3 for gradient and text-shadow in button with a separate css bootstrap-theme.css.
I'l send the alpha version (1.0) :D 

### jQuery ui button Bootstrap 3

![jquery-ui-button-bootstrap3](https://f.cloud.github.com/assets/356674/1015961/345cdfda-0bec-11e3-8d7f-ecf2f9a1b475.png)

**Comment by billschaller** [comment]
@gtraxx I am very much looking forward to this -- good work :)

**Comment by roemera** [comment]
@gtraxx Let me know if you need any help. Cheers.

**Comment by gtraxx** [comment]
Hi, I'l send the CSS version soon but I have not checked the Less Version.
Thanks ;)

**Comment by dharapvj** [comment]
Once you have added your normal CSS version - I will work on converting it to LESSed version.

In the meanwhile I am getting acquainted with BS3

**Comment by gtraxx** [comment]
@dharapvj Thanks for support :D

**Comment by addyosmani** [comment]
This looks great. Are you committing your work directly to the masterbs3 branch?

**Comment by gtraxx** [comment]
Hi @addyosmani ,
I send the new version in masterbs3 ;) but I have not finished, there is still work.
This is a pre alpha version ;)

View commit : https://github.com/addyosmani/jquery-ui-bootstrap/commit/3b3a76a95b4b8b8b54670b13af719bdc2595c1c4

**Comment by addyosmani** [comment]
Nice work, @gtraxx! Just checked again. Preview for anyone interested:

![screen shot 2013-09-01 at 22 01 05](https://f.cloud.github.com/assets/110953/1064706/c6500b4c-1349-11e3-8444-3a15799f7230.png)

As far as I can tell there's still a lot of work to do to replace the existing BS2 styles with the simpler BS3 ones but this work is coming along nicely :)

**Comment by juristr** [comment]
Awesome guys!

**Comment by gtraxx** [comment]
thanks :)

Note : For gradiant support used "jquery-ui-1.10.3.theme.css" ;)

**Comment by jdart** [comment]
Just wanted to say thanks for your continued efforts towards accomodating bs3!

**Comment by pszittyay** [comment]
Just wanted to say thanks!!!

**Comment by ludo99** [comment]
How may I get access to jquery ui for bootstrap 3?

**Comment by gtraxx** [comment]
Hi,
In the new branch masterbs3 (https://github.com/addyosmani/jquery-ui-bootstrap/tree/masterbs3)
;)

**Comment by dominicwilliams** [comment]
Hi branch looks a little quiet. Have you got an estimate of how much work needs doing to get it usable?

**Comment by mkbaldwin** [comment]
Just curious if there is still work going on to make this work fully with Bootstrap 3 and the new styling?

**Comment by gtraxx** [comment]
New styles bootstrap 3 are defined entirely in version1.0, I corrects any bugs but Less version may not be synchronized ?
View branch masterbs3, I analyze the differences ;)

**Comment by mkbaldwin** [comment]
Cool, will check out the branch then! :)

**Comment by dharapvj** [comment]
Got some time today and checked what is still pending in LESS version...

I am still to get through dialog, slider, tabs, datepicker, progressbar, toolbar, tooltip conversion in LESS.

Will get to it immediately.

**Comment by addyosmani** [comment]
@gtraxx closing this issue as this work is being tracked elsewhere. Can you add a preview of the BS3 work (latest) to the readme if you have time?
