### ISSUE TITLE
Input within a table is infinitely extended in IE7

### ISSUE THREAD

**Issue by palomita1307** [jquery-ui-bootstrap/jquery-ui-bootstrap#203]
As you type in the input, this extends expanding all other components
Codigo:

<table cellspacing="5" cellpadding="5" border="0"  align="center" width="100%" >                                            
    <tr>
    <th align="left" width="20%">Cédula</th>
    <td align="left" width="75%">                                 
            <html:text  name="formBean" property="usuario" size="12"  maxlength="100" styleClass="ampliado numero"/>
    </td>
                                                
    </tr>
    <tr>
        <th align="left">Clave</th>
        <td align="left">                                                       <html:password  name="formBean" property="clave" size="12"  maxlength="10"  />
        </td>
    </tr>
    <tr align="center">
            <td colspan="2">
                                                            <html:button  title="Haga [Clic] para Ingresar " property="enviar" value="Aceptar" onclick="enviarFormulario('Aceptar');return false"   />
            </td>
    </tr>
                                            
    <tr align="center">
        <td colspan="2">
                                                     
                                                            <span>¿Olvido su Clave? </span>
        </td>
                                                
    </tr>
                                                
    <tr align="center">
         <td colspan="2">
            <span >Regístrese </span>
        </td>
                                                
    </tr>
                                        
</table>

![errorie7](https://f.cloud.github.com/assets/5392690/1089593/e6ab5fea-1646-11e3-9d3d-a865cf588223.png)

**Comment by gtraxx** [comment]
Hi,
What version of jquery ui bootstrap ?
Do you have a link for preview ?

**Comment by palomita1307** [comment]
Hi, 
Bootstrap v2.2.2
jQuery UI - v1.10.0 - 2013-01-23
link http://190.147.208.102:8084/registroWeb/cargaloginrup.do
thanks
