### ISSUE TITLE
Dialog & IE Bug

### ISSUE THREAD

**Issue by RedForc** [jquery-ui-bootstrap/jquery-ui-bootstrap#204]
1.Dialog Can not resizable in the new version and last version   (all:chrome & FireFox  )

2.IE is not supported

**Comment by RedForc** [comment]
IE10

**Comment by gtraxx** [comment]
Hi, I'll check in the new version (1.0 alpha) in the repository bs3

**Comment by gtraxx** [comment]
I have no problem dialog resizing with the new version (masterbs3)

![bug-resizing-dialo-2013-9-16](https://f.cloud.github.com/assets/356674/1147327/bc04e772-1ea0-11e3-9c7e-b4167c0c1050.png)

**Comment by gtraxx** [comment]
Hi, The problem is it fixed ? 
Is the latest version (bs3)?
