### ISSUE TITLE
Issue bankruptcy

### ISSUE THREAD

**Issue by addyosmani** [jquery-ui-bootstrap/jquery-ui-bootstrap#211]
With work ongoing to move over to Bootstrap 3, I think we should close all issues related to the older version of the project citing that it will no longer be supported once this new version is out. I think we should also update the readme to reflect this work.

**Comment by gtraxx** [comment]
Hi Addy, the README file is modified but can add information (masterbs3) :)

**Comment by dharapvj** [comment]
I feel that we should continue to support BS2 for some more time. I am quite unsure if people have made the switch yet. 

Also, BS3 is still settling down. Last I checked - they have made whopping 400 commits post v3.0 tag. So people will take some more time to trust BS3 and adaption of the same will take some time.

**Comment by kamalraturi** [comment]
Yes, Please do all updates for BS3 as soon as possible.

**Comment by gtraxx** [comment]
@kamalraturi CSS files are already updated in the branch masterbs3

**Comment by addyosmani** [comment]
@gtraxx If we move this to an org this week do you think we can clean up the issue tracker and point people to the work in progress? The last version is now a little old and it would be great for the tracker to focus on issues with the BS3 work. What do you think?

**Comment by gtraxx** [comment]
@addyosmani, Yes we can move to org but I have to check the work of the Less version.
I'll check the issues and fix bugs :)

**Comment by dharapvj** [comment]
I know.. I am out of picture recently and the LESS version is probably not finished.. I am yet to look at the fixes patches by the @bcullman. But mostly what bcullman has provided is a complete finished product for LESS version too.

I just became father of a cute angel.. :-) so.. its bit overwhelming at the moment to juggle it all.. But my pledge to continue to work for this project is still alive!

**Comment by addyosmani** [comment]
Congrats @dharapvj :) @gtraxx Fantastic. Lets do that soon then. Thank you!

**Comment by addyosmani** [comment]
What would we like to call the org? jQueryUIBootstrap? jQueryBootstrap?

**Comment by addyosmani** [comment]
@gtraxx do you think you might have time in the next few weeks to close any/all issues to do with the older version of jQuery UI Bootstrap so that new users know which issues to do with the new release are still relevant? I'd love for us to be able to replace http://addyosmani.github.io/jquery-ui-bootstrap/ with the newer version. Moving to the org can be done right after the clean-up and alpha/beta push to that page.

Btw, do you have a preference on org name? Just checking before I create and move it over.

**Comment by gtraxx** [comment]
Hi @addyosmani , Yes I will close tickets from jquery ui 0.5 bootstrap
You can view the new version instead of the old

> Btw, do you have a preference on org name? Just checking before I create and move it over.
- jquery-ui-bootstrap.org

Do you have any other suggestions ?

**Comment by addyosmani** [comment]
Oh, I meant name for the GitHub organisation I create to transfer this repo over to :)

**Comment by gtraxx** [comment]
lol, UI Bootstrap Team hahaha

JQ Bootstrap Or UI Bootstrap , I have no idea :/  A suggestion ?

**Comment by gtraxx** [comment]
Hi @addyosmani, I closed some issues but can we switch the display on bs3 ?

**Comment by addyosmani** [comment]
@gtraxx I've created the organization `jquery-ui-bootstrap` and moved the repo over to there. It should automatically redirect correctly for all users. 

Do you need me to do anything in order to publish a preview of the site? I assume that the site we used to use at addyosmani.github.com/../ will be something we'll replace with jquery-ui-bootstrap.github.com or similar. 

Could you get that setup when you have a chance? I'm happy to flip the switch on anything I need to, but otherwise yes 100% to us turning on BS3.
