### ISSUE TITLE
Secondary icon in ui-button breaks button layout

### ISSUE THREAD

**Issue by pontikis** [jquery-ui-bootstrap/jquery-ui-bootstrap#215]
Here is what I mean

![jquib](https://f.cloud.github.com/assets/814012/1274716/8fb69450-2dc7-11e3-9ff1-7b62f2111422.png)

I wrote a workaround here http://www.pontikis.net/blog/jquery-ui-bootstrap-ui-button-icon-secondary  but I don't think that is a permanent solution.

Congrats for your great project.

**Comment by gtraxx** [comment]
Hi,
Do you have the same bug with the online demo ?

**Comment by pontikis** [comment]
Good morning!

this **is** a screenshot **from online demo**
http://addyosmani.github.io/jquery-ui-bootstrap/components.html

just replacing 'primary' with 'secondary' in  

```
$("#button-with-icon" ).button({
    icons: {
        primary: "ui-icon-locked"
    },
    text: true
});
```

of http://addyosmani.github.io/jquery-ui-bootstrap/assets/js/demo.js
