### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by jainils** [jquery-ui-bootstrap/jquery-ui-bootstrap#231]
Hey, I am not sure if this is the right place to post. 
I was using this site
http://addyosmani.github.com/jquery-ui-bootstrap but it no longer seems to be up.

**Comment by deguzmanreloader** [comment]
Yes.. The site is down.

**Comment by noinkling** [comment]
http://jquery-ui-bootstrap.github.io/jquery-ui-bootstrap/

**Comment by deguzmanreloader** [comment]
Great! I thought this plugin already gone. Thanks so much!!!

**Comment by gtraxx** [comment]
Thanks, I change the url ;)
