### ISSUE TITLE
Live Preview link is broken.

### ISSUE THREAD

**Issue by mikecole** [jquery-ui-bootstrap/jquery-ui-bootstrap#233]

**Comment by gtraxx** [comment]
New link : https://github.com/jquery-ui-bootstrap/jquery-ui-bootstrap

But it is the old version, I need to copy the project to bs3 preview

**Comment by gtraxx** [comment]
Demo with version 1.0 alpha is available ;)

http://jquery-ui-bootstrap.github.io/jquery-ui-bootstrap/
