### ISSUE TITLE
Hardcoded input width breaks bootstrap

### ISSUE THREAD

**Issue by tjoneseng** [jquery-ui-bootstrap/jquery-ui-bootstrap#24]
This CSS:

input[type="text"],
input[type="password"],
.ui-autocomplete-input,
textarea,
.uneditable-input {
  display: inline-block;
  width: 210px;
  height: 18px;
  padding: 4px;
  font-size: 13px;
  line-height: 18px;
  color: #808080;
  border: 1px solid #ccc;
  -webkit-border-radius: 3px;
  -moz-border-radius: 3px;
  border-radius: 3px;
}

Breaks the Bootstrap grid system (e.g., <input class="span7" ...> (and most likely application CSS that also set input width because the specificity takes precedence.  You shouldn't be hardcoding widths of generic elements like this.

**Comment by addyosmani** [comment]
@tjoneseng thanks for catching this. I agree that hardcoded widths should definitely not be used here - I'll fix this tomorrow.
