### ISSUE TITLE
jQueryUI  1.11.1 

### ISSUE THREAD

**Issue by leixu2txtek** [jquery-ui-bootstrap/jquery-ui-bootstrap#255]
please update to the lastest version of jQueryUI  1.11.1 

add the selectmenu css ..

thank you  very much

**Comment by philwig** [comment]
Looks like I'm going to have to do this - add in CSS to make jQueryUI SelectMenu look pretty with the rest of this and Boostrap. Or has anyone already done this?

**Comment by philwig** [comment]
That was actually 2 lines of CSS, only 1 of which is relevant to this. Not really an issue then.

**Comment by leixu2txtek** [comment]
:)
