### ISSUE TITLE
ui.bootstrap.collapse animation jumps when padding is added to element to be animated

### ISSUE THREAD

**Issue by Waterstraal** [jquery-ui-bootstrap/jquery-ui-bootstrap#259]
When using the collapse directive on an element that has padding on it, the animation is not smooth but jumps the remaining padded pixels.

I have prepared a plnkr demonstrating the issue: http://plnkr.co/edit/iHZHPYRgGdbouRUyh5xn?p=preview

**Comment by Wol-3** [comment]
hey
