### ISSUE TITLE
CSS styled file input

### ISSUE THREAD

**Issue by LKay** [jquery-ui-bootstrap/jquery-ui-bootstrap#28]
As you asked, separet issue for this feature.

Maybe you could make bootstrap like styling for file input using http://www.filamentgroup.com/lab/jquery_custom_file_input_book_designing_with_progressive_enhancement/ ?

With that, just like with regular inputs you could make width controling styles span1 - span12 as custom input does not work well with auto size width. 

I used this method before in some of my projects, worked quite nice. There is only a small bug with IE (I don't remember if it was 6 or 7) with flowing input which was few px further than end of input so clicking wasn't woring at the edge. I dod some fix some time ago, I'll look for it.

**Comment by panosru** [comment]
I like the idea so I started working on it :) I need to do some enchants on filament's script (not that ti's not good) in order to make it more configurable :)

Sneak peak: ![custom file upload](http://dl.dropbox.com/u/16165490/Screenshots/jquery-bootstrap-upload-file.png)

**Comment by panosru** [comment]
@LKay check this https://github.com/addyosmani/jquery-ui-bootstrap/pull/31
