### ISSUE TITLE
LESS sources?

### ISSUE THREAD

**Issue by panosru** [jquery-ui-bootstrap/jquery-ui-bootstrap#29]
Hello, it would be great to have less files in order to see the changes made in original bootstrap less files.

**Comment by addyosmani** [comment]
Slated for sometime after version 1.0. Just want to ensure the theme is stable across all components and states before we add in LESS sources :)

**Comment by panosru** [comment]
Hello Addy, thanks for the reply! Well I can't see how this could affect the current development process. What I did is I compiled twitter's bootstrap less into CSS and applied a diff wit the bootstrap.css of this project and then I applied the differences on twitter's bootstrap less files. The only changes I saw was actually some altering of the filter and some others properties and from form.less you comment some code because it breaks the layout in jquery ui and same for reset.less, I actually prepend .bootstrap class for these definitions instead of commenting them in order to be able to use them everywhere I need them without breaking the compatibility with jquery ui neither with twitter bootstrap.

**Comment by addyosmani** [comment]
@panosru Oh! I originally read this as wanting to move the entire theme (i.e modified bootstrap + jQuery UI theme over to LESS). If we're just talking about the bootstrap portion that would be absolutely fine. We could probably get that into one of the releases being made over the next week or two. 

Would you like to make a PR against master with a `less` folder and the above in it?

**Comment by panosru** [comment]
sure I will do it once I get back @ home :) I will post back here :)

**Comment by panosru** [comment]
Hi! I created a pull request, I didn't knew how to add it on existing issue though... :/

**Comment by addyosmani** [comment]
Hi @panosru. No worries at all! We can just reference https://github.com/addyosmani/jquery-ui-bootstrap/pull/30 here and I'll clean it up later. In terms of testing, have you compiled the LESS files and made sure that the output has no visual difference compared to the patched bootstrap file? I assume there wouldn't be but just checking before a merge occurs.

Thanks again!

**Comment by panosru** [comment]
Hello, yes I had no visual difference but you can test it too :) ´lessc css/less/bootstrap.less > css/bootstrap.css´ :)

**Comment by addyosmani** [comment]
@panosru looks good! cheers! I'll get this merged. Thanks again.

**Comment by addyosmani** [comment]
Just landed this. Closing.
