### ISSUE TITLE
CSS styled select

### ISSUE THREAD

**Issue by LKay** [jquery-ui-bootstrap/jquery-ui-bootstrap#34]
jQuery UI team is developing plugin/widget to style select forms input. It is currently in jQuery UI Labs and probably will be added to official release some time. Maybe you should style it bootstrap like in advance?

http://www.filamentgroup.com/lab/jquery_ui_selectmenu_an_aria_accessible_plugin_for_styling_a_html_select/
https://github.com/fnagel/jquery-ui
https://github.com/fnagel/jquery-ui/wiki/Selectmenu

**Comment by panosru** [comment]
I personally use chosen with twitter bootstrap and to be honest I like it more than filament's select approach, I used filament's approach more than a year ago (about when they released this approach) and back then was ok but now I find chosen much better to work with and more featured too :)

http://harvesthq.github.com/chosen/

**Comment by fabriziofortino** [comment]
@panosru Have you customized the chosen css to work with bootstrap style? I am trying to make them working together but so far I cannot display the chosen multiple select properly. 

Thanks

**Comment by panosru** [comment]
@fabriziofortino I dropped chosen to be honest and I use [select2](https://github.com/ivaynberg/select2) which is an extend of chosen much better! :)

**Comment by fabriziofortino** [comment]
@panosru I fixed the problem with chosen: I was calling the chosen() function on a select that was not yet displayed so the width was set to 0px. Btw thank you for the select2 link: it looks very interesting!

**Comment by rabu81** [comment]
hi, I have done some quick css overwrites to make parts of _chosen_ match the Bootstrap form styling, see it here: https://gist.github.com/2841808
