### ISSUE TITLE
Possibility to use pills for tabs

### ISSUE THREAD

**Issue by paglias** [jquery-ui-bootstrap/jquery-ui-bootstrap#35]
it would be cool if we could use pills style tabs http://twitter.github.com/bootstrap/#navigation

**Comment by addyosmani** [comment]
So, I'm trying to think about how we would go about letting people do this with the jQuery UI tabs. It might be that we have a custom pills namespace that has to be specified as a class when defining the markup for the tabs and this isn't hugely different to what Twitter Bootstrap does. 

If someone would like to try getting a PR for this together, happy to review. If not, it'll probably have to wait until the theme reaches 0.5 so I have more time to get it done.

**Comment by paglias** [comment]
What about this: just add a class 'pills' to the tab's div then in css
have all style for it like this .pills > .ui-tabs-nav

**Comment by zowber** [comment]
that, or use idPrefix http://jqueryui.com/demos/tabs/#option-idPrefix

**Comment by addyosmani** [comment]
@paglias hadn't considered that before. Worth experimenting with!
