### ISSUE TITLE
problem with buttons

### ISSUE THREAD

**Issue by fawwaz** [jquery-ui-bootstrap/jquery-ui-bootstrap#36]
hi .. i run the test in this folder : …/bootstrap/js/tests/index.html

and i get some message like this one : http://prntscr.com/5da78

can you tell where the problem is ? i am not expert in using Javascript..

**Comment by addyosmani** [comment]
That folder shouldn't be getting included (it's testing for bootstrap-specific JS components, which this pack doesn't use). I'll remove it for the next .x release. If you try using/accessing the main index, you shouldn't run into any problems.

**Comment by fawwaz** [comment]
since i am not so expert in jquery and javascript, can you give me a documentation how to use your library ? i love that

**Comment by addyosmani** [comment]
@fawwaz The base index.html file is actually the same template you'll find provided by any of the themes over at jqueryui.com. I recommend reading through it and the various code samples as this is the  best way to understand how the various widgets work.
