### ISSUE TITLE
Forms inside a modal dropdown not editable

### ISSUE THREAD

**Issue by et** [jquery-ui-bootstrap/jquery-ui-bootstrap#40]
Bear with me on this, I'm trying something ridiculous. Essentially, I have a form inside a [dropdown menu](http://twitter.github.com/bootstrap/javascript.html#dropdown) which is inside a [dialog](http://jqueryui.com/demos/dialog/)

For whatever reasons, the input fields inside the dropdown are not editable. Input fields outside the dropdown are.

Here is a repository that demonstrates the issue: https://github.com/et/dropdown-experiment

Here are screenshots of what I'm talking about:

Input field editable outside dropdown
![editable](http://i.imgur.com/qIPbb.png)

Input fields not editable within dropdown.
![uneditable](http://i.imgur.com/tpb8t.png)

I've tried tweaking with firebug to isolate the issue but cannot determine what the cause is.

**Comment by panosru** [comment]
This happens because modal window have z-index of 1002 and the overlay have z-index of 1001 but ul.dropdown-menu have z-index of 900 as a result you can't interact with it as you supposed too...

With first glance in order for this to be fixed `z-index: 900;` need to be removed from `.menu-dropdown, .dropdown-menu {` but I'm not sure what side-effect this will cause.

**Comment by nexenator** [comment]
I experience a similar issue opening a tinymce 4 editor within a modal dialog. The editor itself is working great but fields within dialogs opened by the editor (links, files, source, etc) are not focusable.

Any suggestions on this?

![image](https://f.cloud.github.com/assets/207409/622972/0ec1563a-cf55-11e2-9993-db3222425011.png)

(When clicking into an input field or textarea, only the ok-button below the top modal is focused)

**Comment by lucazen** [comment]
Sorry guys,
i still experience this issue in bootstrap 3, did you find any fix?

Thank you!
Luca
