### ISSUE TITLE
jplayer theme

### ISSUE THREAD

**Issue by lightglitch** [jquery-ui-bootstrap/jquery-ui-bootstrap#46]
It would be nice to have a theme for http://jplayer.org/ but it's probably needed to do it from scratch.

**Comment by addyosmani** [comment]
Is there a reason you prefer jPlayer over other solutions? I think a video theme would be an interesting future addition, but I'd like to ensure we select a solution that's recognised as proving the best balance between HTML5 support and Flash fallbacks.

**Comment by lightglitch** [comment]
The only reason is that is based on jQuery and also  supports audio playlists, for me the best ones are:

http://jplayer.org/ and http://videojs.com/ 

but could be more that I don't know.

**Comment by tim-peterson** [comment]
i agree the playlist functionality sets apart jplayer, would be nice if it could have a better theme, the jplayer circle player would be even better!

**Comment by addyosmani** [comment]
Looking at the list of features we need to implement for V2 of this project, I think we're going to end up focusing on UI components that developers can use to build web apps. As such I'm going to close this feature request as patchwelcome. If someone would like to submit a PR with the work included we'd be happy to merge.
