### ISSUE TITLE
Chrome, primary button in dialogs is "selected"

### ISSUE THREAD

**Issue by paglias** [jquery-ui-bootstrap/jquery-ui-bootstrap#48]
As you can see in this image when opening a dialog in chrome (i've not tested in other browsers) the primary button has a golden border like the one wee see in focused text input and around some links, It disappear after clicking somewhere
![Alt text](http://img7.imagebanana.com/img/dkqgi8hl/Selezione_001.png)

It's not a priority but it's not very nice to see it

**Comment by addyosmani** [comment]
This has been in since 0.1 and I agree - it doesn't look great. I think we should be okay to remove it.

**Comment by peol** [comment]
I agree, IF there's a focus-style on the button. It's easily removed with `outline: 0;`.

**Comment by addyosmani** [comment]
Cheers @peol. I'll aim to get this one taken care of this week (unless anyone else submits a PR before that).

**Comment by Francisc** [comment]
I can do that. Do you want the focus to be removes for all ui-button classed elements, or just ones in the .ui-dialog-buttonset?
Or perhaps should JavaScript not set focus on a button at all, thus preventing the focus halo to appear unless user clicks it.

**Comment by addyosmani** [comment]
@Francisc thanks. I think we should be okay just removing it from the dialog for the moment. We can revisit removing it from the other types of buttons if it becomes a problem there.

**Comment by Francisc** [comment]
OK, so CSS solution not JS.

**Comment by addyosmani** [comment]
@Francisc Ideally yes. Wherever possible with this theme I'd like for us to make changes using the presentation layer rather than resorting to JS. I see you've just sent a PR upstream so I'll review and hopefully merge in the morning :)

**Comment by Francisc** [comment]
OK. Thank you.

**Comment by Francisc** [comment]
This should be closed.
