### ISSUE TITLE
Slider dragging issue

### ISSUE THREAD

**Issue by lightglitch** [jquery-ui-bootstrap/jquery-ui-bootstrap#5]
My slider has a weird behavior, the background color and the picker are not synchronized with the mouse dragging.

The official JQuery UI slider have the correct behavior.

Tested on Firefox 8 e latest Chrome

**Comment by addyosmani** [comment]
This appears to be okay in latest (as of a few minutes ago). Could you re-confirm that it's still an issue?

**Comment by lightglitch** [comment]
It's ok on the latest, closing it.
