### ISSUE TITLE
 Filament Group File Input issue

### ISSUE THREAD

**Issue by alexfigueiredo** [jquery-ui-bootstrap/jquery-ui-bootstrap#53]
The input field shrinks every time a file is selected.

**Comment by panosru** [comment]
Could you give a chunk of code so we could reproduce it? Or a live example, anything that could help :)

Thanks

**Comment by alexfigueiredo** [comment]
You can see it here http://addyosmani.github.com/jquery-ui-bootstrap/
Try to select a file, then do it again...

I've tested at Chrome 17.0.963.46, Firefox 10, IE9

**Comment by panosru** [comment]
Hahaha it's funny! :P indeed it's a bug :P Sorry when I made it I didn't though of trying to add files again :P

I'll take a look into that :)

**Comment by panosru** [comment]
@alexxfsilva [this](https://github.com/addyosmani/jquery-ui-bootstrap/pull/54) should work for you :)

**Comment by alexfigueiredo** [comment]
Wow! That was fast...
Thank you!

**Comment by panosru** [comment]
:) np

**Comment by effectjam** [comment]
Thanks for fixing above issue, I update as in "#54 from panosru/patch-1.." but I found another issue on Chrome only, not on IE and Firefox, when choosing then change and cancel. It seems to shrink in vertical.
