### ISSUE TITLE
Support for jqGrid

### ISSUE THREAD

**Issue by paulsperanza** [jquery-ui-bootstrap/jquery-ui-bootstrap#58]
I would love to see support for triands' jqGrid. 

http://trirand.com/blog/jqgrid/jqgrid.html

I took a quick stab at substituting the jquery ui css for it and the problem with the bootstrap css is that the jqGrid uses dialog and accordion classes so it get a white title bar with silver header and footers. If anyone has an idea of a way to make this look good I'm all ears.

Great job Addy -

Paul Speranza

**Comment by addyosmani** [comment]
Thanks. This is actually something I've experimented with before (see http://addyosmani.com/blog/jquery-ui-bootstrap-0-2-released/) and I plan on addressing it in more depth after we've moved onto Bootstrap 2.0.

**Comment by panosru** [comment]
@paulsperanza personally I'm not really fun of those implementations, not that is not good but I believe it's more strict into a certain UI lib with viewports etc, like Dojo or ExtJS, of course with the proper CSS it may be adopt into bootstrap no question about it but to be honest I never worked with it...

**Comment by benli2023** [comment]
+1

**Comment by addyosmani** [comment]
I've been getting requests for the next version of the project to include Bootstrap styles for jqGrid and a number of other components. I'll try to bring these back in. 

Related somewhat:
- Alternatively, if we want to go in the direction of using datatables http://datatables.net/media/blog/bootstrap/001.html, http://datatables.net/blog/Twitter_Bootstrap_2
- jqGrid + font awesome: http://www.ok-soft-gmbh.com/jqGrid/FortAwesome/FortAwesome.htm

**Comment by addyosmani** [comment]
I've included a version if this demonstrated on the site.
