### ISSUE TITLE
generation from .less

### ISSUE THREAD

**Issue by evoskuil** [jquery-ui-bootstrap/jquery-ui-bootstrap#60]
It would be very helpful if jquery-ui-bootstrap could be generated from a .less definition that in turn takes dependencies on the bootstrap .less variables file.

**Comment by evoskuil** [comment]
just noticed that this has been added in the last few days - great to see

**Comment by panosru** [comment]
As you can [see](https://github.com/addyosmani/jquery-ui-bootstrap/tree/Bootstrap2-Dev/css/less) in the upcoming version of this project most of the css are written in less
