### ISSUE TITLE
DateRangePicker conflict with code prettify

### ISSUE THREAD

**Issue by panosru** [jquery-ui-bootstrap/jquery-ui-bootstrap#61]
It seems that DateRangePicker conflicts with [google-code-prettify](http://code.google.com/p/google-code-prettify/) most of the times you don't need code prettify but in case you want it, consider removing DateRangePicker :)

**Comment by addyosmani** [comment]
I think we should probably document this as a part of the wiki.

**Comment by panosru** [comment]
Probably for jQuery UI Bootstrap2 we will need a new page in wiki :P 

Regarding DateRangePicker I personally never liked it and the first thing I do in my projects is to remove it :P I used it couple of times but I believe it is too heavy for most of the needs with date picking.

I have my own simplified version of it which I use. We can either stick with it, or provide our own version of it (of course with a reference on Filament Group) but it is something that we should revisit once the upgrade to bootstrap 2 is done.

**Comment by addyosmani** [comment]
@panosru I'd like to keep the DateRangePicker as a part of the project, but as part of the 2.0 migration, I want us to more clearly separate the third party plugins from the rest of the project. They'll probably each have their own demo page to avoid us loading/theming 5+ third party widgets on the same page.

**Comment by panosru** [comment]
I believe (as you too) that jQuery UI Bootstrap 2 should focus **only** on bringing the jQuery UI components visually as close possible to Bootstrap 2, this is the goal I think of the project otherwise it should be renamed :P if I'm correct then I think we could have 3rd party and custom modules separated in **vendor** folder and have a demo page for each vendor individually.
