### ISSUE TITLE
Resizable not working in combination with Bootstrap 2.0

### ISSUE THREAD

**Issue by pltaylor** [jquery-ui-bootstrap/jquery-ui-bootstrap#62]
I realize there is an on-going discussion about how to implement 2.0 but this JSFiddle shows how the resizable functionality doesn't work when used in conjunction with 2.0.

http://jsfiddle.net/pltaylor3/9WZ7j/

**Comment by addyosmani** [comment]
I don't believe we've yet tested resizable behaviours with Bootstrap and jQuery UI, but if there's a confirmed issue with this we'll definitely do our best to normalize it again.

**Comment by pltaylor** [comment]
I'm going to dig further into it on my end tomorrow....but I figured I would bring it to your attention.

**Comment by addyosmani** [comment]
Thanks to bringing it to our attention :)

**Comment by addyosmani** [comment]
Closing this as we've agreed to do it as a part of 2.0.
