### ISSUE TITLE
ui theme-able?

### ISSUE THREAD

**Issue by geekbuntu** [jquery-ui-bootstrap/jquery-ui-bootstrap#66]
hi, nice integration of projects, just wondering if themroller is still an option?

thanks for the work Addy.
tia,

**Comment by addyosmani** [comment]
For the most part this should still be able to work with Theme-roller. There are aspects of the project (e.g bootstrap.css) which we might have to discuss though - would someone expect these styles to be applied to the rest of the document or just those styles that affect the UI components (I would say the latter makes the most sense).

**Comment by geekbuntu** [comment]
simply adding the jq-ui them out of the box, it doesn't seem to effect much.  it almost seems it would be counter-intuitive to try to apply style changes (as in why were you using bootstrap... exactly?) :-D

if i have any extra time, i will try to test widgets - outside the scope of bootstrap.

**Comment by priscillahuang** [comment]
any chance to get the themeroller URL for this bootstrap theme? would be great, thanks!

**Comment by geekbuntu** [comment]
from what i've seen/tried - it looks easier to just approach styling from the boostrap perspective. not to mention, there are a lot of designers liking bootstrap - so themes are popping up quickly.
