### ISSUE TITLE
Split Button Design Issue?

### ISSUE THREAD

**Issue by lightglitch** [jquery-ui-bootstrap/jquery-ui-bootstrap#7]
![](http://i43.tinypic.com/dww8k7.png)

On top latest Chrome, on the bottom firefox 8.

**Comment by lightglitch** [comment]
Also looks bad on IE 9

**Comment by addyosmani** [comment]
Confirmed in FF8/9.

**Comment by addyosmani** [comment]
btw, thank you for posting about these issues. If there is anything else at all you notice, feel free to post more and I'll make sure to fix.

**Comment by panosru** [comment]
Ok for IE9 (until IE10 will come out) but why supporting FF8 ? FF9 is stable and FF10 is almost ready to be released...

**Comment by addyosmani** [comment]
@panosru check the comment date :) I believe FF8 was still around back in December which is why I may have mentioned support for it. I also generally make sure to test against older versions based on statcounter to ensure that we don't leave support for edge-cases out of the loop

**Comment by panosru** [comment]
if I'm correct I think back then ff 9.0.1 was already stable :) Personally I don't support browsers that are not supported any more and besides that I strongly believe users should update their browsers for various reasons :)

**Comment by zowber** [comment]
...plus, it's likely that if it looks right in FF10 it'll look right in FF8 anyway. Right?

**Comment by Heliosmaster** [comment]
Still there with FF11 (stuck with an old LTS at work, can't upgrade to newer FF)
