### ISSUE TITLE
Bootstrap Plugin Test Suite failed on 'Buttons'

### ISSUE THREAD

**Issue by syndrael** [jquery-ui-bootstrap/jquery-ui-bootstrap#70]
Hello,
When i try this page: bootstrap/js/tests/index.html
i get errors on buttons:
42. bootstrap-buttons: should return set state to loading (2, 2, 4)Rerun

```
btn text equals mdo
Expected:   "mdo"

btn text equals fat
Expected:   "fat"

btn is disabled
btn has disabled class
```

and:

bootstrap-buttons: should return reset state (2, 5, 7)Rerun

```
btn text equals mdo
Expected:   "mdo"

btn text equals fat
Expected:   "fat"

btn is disabled
btn is disabled
btn text equals mdo
Expected:   "mdo"

btn is not disabled
btn does not have disabled class
```

I've tried it on Firefox 12 and Chromium 20.
Best regards
S.

**Comment by addyosmani** [comment]
My apologies. The test suite was pulled from Bootstrap but isn't being applied to the current project. The next version may however come with its own test suite.
