### ISSUE TITLE
Ui-Button-Primary

### ISSUE THREAD

**Issue by all3nT** [jquery-ui-bootstrap/jquery-ui-bootstrap#77]
I am unable to get the ui-button-primary effect to show up when I have buttons in a dialog box. The ui-button-primary effect works fine on buttons everywhere else. I can create ui-button-primary buttons in the dialog by use the dialog button attribute. However, this is annoying because it prevents me from customizing the location of my buttons in the dialog box. The current method limits the ui-button-primary buttons to only the bottom of the dialog box.

Thanks

**Comment by wyqydsyq** [comment]
Why not just use the native bootstrap `.btn` and `.btn-primary` for buttons in the content of a dialog?

**Comment by all3nT** [comment]
Great idea. I forgot that those native classes where included. I will give it a try.

**Comment by all3nT** [comment]
Thanks, it worked with .btn and .primary.

**Comment by sheymann** [comment]
Hi, how do you add the buttons to the dialog? I can't find how to bind click events on them.

**Comment by all3nT** [comment]
Here are some examples:

For a primary button in the dialog put this in the html of your dialog:

<div class="btn primary" id="handler">I am a button</div>


Then use this in your js

$("#handler").click(function()
{
//do something amazing here
});

or for just a normal this works

```
$("#handler").button().click(function()
{
//do something amazing here
});
```

You can also declare buttons in your dialogs,
http://jqueryui.com/demos/dialog/#modal-confirmation

$( "#dialog-confirm" ).dialog({
            resizable: false,
            height:140,
            modal: true,
            buttons: {
                "Delete all items": function() {
                    $( this ).dialog( "close" );
                },
                Cancel: function() {
                    $( this ).dialog( "close" );
                }
            }
        });

**Comment by sheymann** [comment]
Hey thanks, sorry for the late reply.
