### ISSUE TITLE
Is this project dead? Lets get it rolling again.

### ISSUE THREAD

**Issue by nilskp** [jquery-ui-bootstrap/jquery-ui-bootstrap#78]

**Comment by addyosmani** [comment]
Project isn't dead. We have plans on updating in a few weeks once releases
for some other projects are out the door.

On Tuesday, June 26, 2012, nilskp <
reply@reply.github.com>
wrote:

> No changes in 5 months.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/addyosmani/jquery-ui-bootstrap/issues/78

## 

_Addy Osmani_

Developer Programs Engineer at Google
Blogger at: http://addyosmani.com
Phone: +44 7501 594 382

**Comment by ghost** [comment]
I thought it was dead as well.

**Comment by corleroux** [comment]
It's far from dead.
I am not contributing, only following (shameful). But recently jquery-ui 1.9 has been ported successfully.

Cor le Roux

-----Original Message-----

**Comment by gtraxx** [comment]
Yes I sent the changes for jQuery 1.9.0 with additional demos

https://github.com/addyosmani/jquery-ui-bootstrap/tree/Boostrap-1.9.0

Aurelien Gerits :)

**Comment by addyosmani** [comment]
Project isn't dead. I've tried restarting it a few times but really need
help from some dedicated contributors for a week or two to get it on parity
with Bootstrap latest.

Short of folks being able to help with this we'll have to wait until I have
more free time to do the upgrades myself and get out a new release.

If you'd be willing to help with specific areas I'm happy to assign areas
that need more work. I could be wrong, but as one of the most popular
jQuery UI themes out there this would be a nice opportunity to contribute
to open source if you're interested :)

**Comment by webbushka** [comment]
@addyosmani I'd love to help out with this! Let me know what I can do.

**Comment by addyosmani** [comment]
@webbushka excellent :) I'll reach out over the weekend with a few ideas of where you might be able to assist. Thanks for volunteering!

**Comment by webbushka** [comment]
@addyosmani sounds great! Looking forward to it.

**Comment by gtraxx** [comment]
@addyosmani: I will follow jQuery UI to be updated and also change the javascript view to improve the structure.
Boostrap jQuery will be included in my new open source software to evolve is therefore a good thing, I will contribute a maximum ;)

**Comment by addyosmani** [comment]
So, it looks like we're going to kick-start this project again. Let's base any further work done on the excellent updates @gtraxx has done for [1.9 compat](https://github.com/addyosmani/jquery-ui-bootstrap/tree/Boostrap-1.9.0) :) I've re-opened this issue and changed the title just to give us a focal point to work from.

Looking through [Bootstrap 2.1.1](http://twitter.github.com/bootstrap/index.html), it would be useful for us to target support on a per page basis so we can cross off what we support/need more work on:
- Scaffolding: http://twitter.github.com/bootstrap/scaffolding.html I believe most of this will work fine with what we have at the moment. 
- Base CSS: http://twitter.github.com/bootstrap/base-css.html The changes here begin with the Forms section, which includes updates to search and other input types. Buttons need to be updated, but from what I've inspected the changes here would be minimal. We'd probably get images and glyphicons for free.
- Components: http://twitter.github.com/bootstrap/components.html from what I can tell, almost all of the different sections here have had updates from 1.x and we'll probably want to tackle them one at a time. If you feel like you'd like to address a specific section, please feel free to go for it.
- JavaScript: http://twitter.github.com/bootstrap/javascript.html There have been visual changes made here along with a few other plugins having been added. Please note that although these are implemented as jQuery plugins, the approach we've been taking has been using native jQuery UI functionality (or jQuery UI plugins to minimize code bloat) where possible. If however we can't do this, we can just use the jQuery plugin from Bootstrap to help with parity.

In case anyone is wondering about LESS:

I've decided that for this next release, we're not going to target using LESS, although we have branches that began trying to do this. It's great and makes sense in a ton of workflows, but looking at the amount of work we have ahead of us to upgrade this project to Bootstrap 2.1.1, I really want to get us visually and functionally on-par with as few barriers as possible between contributors and helping out.

**Comment by gtraxx** [comment]
Ok I'll see what I can do in my own projects drawing resources and analyze the links and changes bootstrap.

I'll have a little fun with javascript, I have read your book on the web: http://www.addyosmani.com/resources/essentialjsdesignpatterns/book/  and I hope to find a French version in addition to your version :)

I find this very interesting resource: http://fortawesome.github.com/Font-Awesome/#all-icons, it looks like typicon :)

**Comment by addyosmani** [comment]
@gtraxx It certainly does have some similarities with typicon, but expanded a little for Bootstrap/web development :)

@yatabani @webbushka if you're still interested in helping it would be awesome if we could get a start on the Base CSS and Components sections I described above. If you think you can help, please feel free to let us know what you'd like to focus on so that we can avoid overlap :)

**Comment by gtraxx** [comment]
ok I go to work glyphicon on it based on http://fortawesome.github.com/Font-Awesome/#all-icons
But also on javascript to view and integrated changes Boostrap 2.1.1

**Comment by corleroux** [comment]
Hi,

Please keep me updated as well. I will be able to contribute from next weekend when I can get a computer again. Looking forward to helping out and getting more involved!

Cor

Cor le Roux

-----Original Message-----

**Comment by addyosmani** [comment]
That sounds great!

**Comment by webbushka** [comment]
@gtraxx Not sure how far you got on the font icons, but thought I'd throw this out there for you. Icomoon is an awesome app that you can use to create your own fonts based on icons, you can upload vector images or full font faces and choose from them to create a font of everything you actually need. Let me know if you need help with that at all. Here is a link: http://icomoon.io/app/
