### ISSUE TITLE
Bootstrap 2 LESS branch

### ISSUE THREAD

**Issue by foxel** [jquery-ui-bootstrap/jquery-ui-bootstrap#80]
How soon this branch will be usable?
Some things are hardly broken for now:
- tabs are not aligned
- colors are not inherited from bootstrap config

**Comment by addyosmani** [comment]
This branch was abandoned but we plan to rewrite the project to use
Bootstrap 2 in a week or so.
On Jul 5, 2012 9:41 AM, "Andrey Kupreychik" <
reply@reply.github.com>
wrote:

**Comment by foxel** [comment]
will it use bootsrap less variables for styling?

P.S. sent a pull request for some changes i made to make it work for me

**Comment by addyosmani** [comment]
@foxel it will indeed. Thanks for the PR! If you're interested in taking part in the Bootstrap 2 sprint to get this project up to scratch happy to let you know when we're doing it.
