### ISSUE TITLE
JQuery UI Layout for Bootstrap

### ISSUE THREAD

**Issue by urobles** [jquery-ui-bootstrap/jquery-ui-bootstrap#83]
Hi Addy,

I know you have been working on the JQuery UI Layout for Bootstrap and wanted to know when it is going to be available for downloading: http://twitter.com/addy_osmani/status/188049479591673856/photo/1

Thanks and keep the good job!

Ulises

**Comment by addyosmani** [comment]
The themed layout component will be available once we've finished the rewrite of this project. We plan to start this in a week or two and as long as we don't run into major issues this should land and be available in 3 weeks. Sorry for the delay!

**Comment by Krzysztof-FF** [comment]
Is your layout component based on jQuery UI Layout Plug-in by Kevin Dalman from http://layout.jquery-dev.net/, or will it be quite independent implementation?

**Comment by urobles** [comment]
Hi Addy,

Thanks for your email. Yes, it is based on the JQuery Plugin that Keven
Dalman wrote, but it won't take much to change it to a new one. I guess
yours integrates with Bootstrap layout manager (you know 12 columns, etc)?

Thanks,

Ulises

On Wed, Jul 25, 2012 at 11:53 PM, Krzysztof-FF <
reply@reply.github.com

**Comment by PunkChameleon** [comment]
Hey all,

Any chance that this has been implemented / is available somewhere? This would be a lifesaver for me right now!!!

**Comment by marccollin** [comment]
it's available?
