### ISSUE TITLE
jQuery timepicker?

### ISSUE THREAD

**Issue by nhodges** [jquery-ui-bootstrap/jquery-ui-bootstrap#84]
I see datepicker has been included, how about timepicker?

https://github.com/jdewit/bootstrap-timepicker

**Comment by addyosmani** [comment]
Is there a screenshot of the timepicker available anywhere? (mobile, but can clone and check myself a little later).

**Comment by nhodges** [comment]
Just snapped one off their demo/documentation for you: http://i.imgur.com/No0gl.jpg

I use it in conjunction with datepicker on one of my projects and they fit together well.

**Comment by addyosmani** [comment]
This seems like an interesting addition. We'll consider it when we're doing the rewrite of this project in a week or two. Thanks!

**Comment by nhodges** [comment]
Not a problem, glad I could contribute two cents. :)

**Comment by addyosmani** [comment]
@gtraxx is this worth adding or should we close?

**Comment by gtraxx** [comment]
ok I add jquery ui timepicker and I adapt the template (http://trentrichardson.com/examples/timepicker/)

**Comment by addyosmani** [comment]
Nice! That would rock. It would be great to have this on the extras page.

**Comment by gtraxx** [comment]
no problem :)

**Comment by ivansammartino** [comment]
Hello, is this added?

**Comment by gtraxx** [comment]
it's work, I had very little time sorry
Aurelien :)

**Comment by ivansammartino** [comment]
NP, thanks! :-)
