### ISSUE TITLE
Script files - what to load and in what order

### ISSUE THREAD

**Issue by rhollhumer** [jquery-ui-bootstrap/jquery-ui-bootstrap#86]
I am having a tough time trying to figure out how to load the scripts. In the demo (Index) page it does not show the bootsrap.js file being loaded at all, so I am not sure how to load the scripts.

Should it be:
1. jQuery
2. jquery-ui-1.8.16.custom.min.js
3. jquery-ui-bootstrap.js (this file in the download: /jquery-ui-bootstrap/bootstrap/bootstrap.js)

The other ones you have in the Index page are for datepicker, wijmo, etc, how do I know if these are optional or required and when should I use them. FOr example do I need to datepicker if I used jQuery-ui-datepicker? ANd if so do I need to exclude the datepicker from my custom jQuery-ui-custom.js file? I might want to use jQuery-ui-1.8.20 instead, what happens then.

I am unsure which files are optional, required and can I use a newer version of jQuery-ui-1.8.20.custom.js or not?

**Comment by Heliosmaster** [comment]
Not sure if this is relevant anymore or closed by #159
