### ISSUE TITLE
Add a Makefile

### ISSUE THREAD

**Issue by fingermark** [jquery-ui-bootstrap/jquery-ui-bootstrap#90]
A Makefile would be nice.

**Comment by addyosmani** [comment]
@gtraxx Do you think we should consider adding in grunt for a build system here over make?

**Comment by gtraxx** [comment]
@addyosmani A makefile will be interesting :)
But who can create ?
Example : 

https://github.com/twitter/bootstrap/blob/master/Makefile

A question! should we change the version number of jquery UI bootstrap ?

**Comment by addyosmani** [comment]
We should definitely change the version number for the next release. Re: the makefile, I could do it. It depends really on what we want it to do. If we're after a similar setup as https://github.com/twitter/bootstrap/blob/master/Makefile it's not to difficult to refactor whats there.

**Comment by addyosmani** [comment]
Maybe we should bite the bullet and just switch over to using Grunt for our build system?

**Comment by Heliosmaster** [comment]
:+1:
