### ISSUE TITLE
Slider Control via Value

### ISSUE THREAD

**Issue by dbmmedia** [jquery-ui-bootstrap/jquery-ui-bootstrap#92]
Hi everybody!

I realy like the Slider form the UI-Bootstrap.
But i have a little problem with it.

I'd like to control the slider via the value
e.g.

In the Input Field ist the value 60 - i change the number to 100.
But the Slider does not grow up :-(.

Can anyone help me to fix this "problem".
Sorry for my bad english, 

Greets from Austria, 
Stefan

**Comment by addyosmani** [comment]
From what I can recall this was a jQuery UI issue. We'll test it again with the latest version of the project in master before release. Thanks.
