### ISSUE TITLE
Star Ratings?

### ISSUE THREAD

**Issue by ryanmac** [jquery-ui-bootstrap/jquery-ui-bootstrap#93]
I'm looking for a static, semantic and microdata-friendly star rating system for bootstrap, less, and/or jquery.  Do you plan on adding star ratings?

**Comment by addyosmani** [comment]
Related http://stackoverflow.com/questions/10144423/twitter-bootsrap-rtl-rating-stars

**Comment by addyosmani** [comment]
Hmm. Gerits do you think we should demonstrate this? We do have font awesome now.

**Comment by gtraxx** [comment]
oh yes with Font Awesome :)
I am preparing a demo

**Comment by addyosmani** [comment]
That's great!

**Comment by gtraxx** [comment]
:)
